### ISSUE TITLE
Auto indent does not work

### ISSUE THREAD

**Issue by lzantal** [DonJayamanne/pythonVSCode#137] opened 2016-05-20 23:22 UTC
Hi,

Just updated my extension and now when I start a for loop or an if statement it does not auto indent after the ":"
This is the only extension I have installed and running on the latest version of VSCode on Mac.

Using the same simple setup on Ubuntu 16.04 auto indent works as expected.

Thank you.

**Comment by markdall** [comment] 2016-05-21 00:02
Reproduced this behavior on Windows 7 Enterprise and what I believe is the latest release of VS Code:
Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:29:20.776Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by MFairley** [comment] 2016-05-21 23:13
I also have this problem on OS X, but particularly when the if or for statement etc. is inside a function.
e.g. 

```python
def foo(test):
    for a in test:
    # does not auto indent here
```

**Comment by mgerner** [comment] 2016-05-23 10:18
Confirm; using extension v 0.3.8 on Code 1.1.1 on Debian. Auto-indenting works if not already indented, but subsequent levels don't work:

```
if True:
    if True:
    # did not auto-indent here
    
def x():
    while True:
    # did not auto-indent here
    
while True:
    try:
    # did not auto-indent here
```

Looking at the commit 67b26c9dcfb17a70f7591d99fb655ae7568945eb , I see that the regex caters for any characters after the keywwords; does the regex perhaps need to similarly cater for (whitespace) characters prior to the keywords? 

On another note, at a glance, I believe the regex is missing the `except` keyword.

**Comment by DonJayamanne** [comment] 2016-05-23 10:21
Fixed, will be in the next release. Thanks for the samples.

**Closed** 2016-05-23 10:24 UTC

**Comment by yuan1238y** [comment] 2016-07-13 03:28
Hello.
I believe the regex is missing the except keyword.
Because i cannot auto indent at except keyword.
I edit extension.js file, add except to regex, this issues has fixed.

**Comment by DonJayamanne** [comment] 2016-07-13 03:52
@yuan1238y , thanks for identifying the issue and reporting it. 
The fix will be available in the next release
