### ISSUE TITLE
Go To Symbol cannot find symbols defined in another file of the project

### ISSUE THREAD

**Issue by ogrisel** [DonJayamanne/pythonVSCode#93] opened 2016-04-22 15:14 UTC
When I open the "Go to Symbol" popup search bar in vscode with the "ctrl+shift+o" on a an open Python file it does not suggest auto-completion on class or function names defined in other Python files of the project. However if I have written the class names in my code, I can run hit "F12" with when the cursor is on it and navigation to the other file works as expected.

Therefore the usefulness of the "Go To Symbol" feature is very limited on projects with a large code base.

Under Atom Editor, I can get this feature by using `exuberant-ctags` (installed with apt-get under Ubuntu or homebrew under OSX) with the following command to generate a `tags` symbol index file at the root of my project folder:

```bash
ctags --python-kinds=-i -R .
```

the I can use the native `shift-ctrl-r` symbol search from Atom to search and navigate to class and function definitions.

Also it would be great if the "Go To Symbol" feature would also index all the Python symbols found under the site-packages folder matching `python.pythonPath`:

```
/path/to/python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
```

Note that this issue has also been reported as a question on stackoverflow:

http://stackoverflow.com/questions/36705579/vscode-python-go-to-symbol-not-working#comment61016176_36705579

**Comment by ogrisel** [comment] 2016-04-22 15:16
Note: I use vscode under Linux (Ubuntu) with Python 3.5 in a virtualenv with appropriately configured `python.pythonPath` in my `settings.json` .

**Comment by DonJayamanne** [comment] 2016-06-09 23:01
I believe this is related to the issue #138

**Comment by DonJayamanne** [comment] 2016-06-29 07:25
Suggestions for #183

**Comment by alexblack** [comment] 2016-08-13 19:28
Same issue here, F12 works to navigate to a symbol in another file, but Go To Symbol won't go to a symbol in another file in the project.

Any work arounds?

**Comment by DonJayamanne** [comment] 2016-09-04 23:39
Closing as this is a duplicate of #138.
@alexblack , @ogrisel , the plan is to create a separate extension that will provide this functionality (for other languages as well).

**Closed by DonJayamanne** 2016-09-04 23:39 UTC
Labels: enhancement

**Comment by ogrisel** [comment] 2018-09-20 08:55
For people finding this issue via google: the requested feature was implemented both with jedi and with the Microsoft language server for Python. At the time of writing I found the following bug that prevents the latter to work properly: #2637.
