### ISSUE TITLE
Feature request: select Python version based on shebang

### ISSUE THREAD

**Issue by nlmalc** [DonJayamanne/pythonVSCode#1160] opened 2017-08-11 11:20 UTC
Could you please use the shebang at the start of the Python script to determine which Python executable to use? My scripts say "#!/usr/bin/env python" or "#!/usr/bin/env python3", which is fairly convention. It's quite annoying having debugging (and linting) failing because it's a Python2 script, but the debugger uses Python3.

I'm on a Mac with the default Python (2) installed as well as Python3 via Homebrew, but this page is quite interesting with regards to the shebangs and how the Python3 launcher interprets them on Windows:
http://testerstories.com/2014/06/multiple-versions-of-python-on-windows/

## Environment data
VS Code version:  Version 1.15.0 (1.15.0)

Python Extension version:  
Python Version:   2.7.10 and 3.6.2
OS and version:   macOS 10.12.6

## Actual behavior
VS Code uses the wrong version of Python when debugging Python 2 scripts

## Expected  behavior
Automatically use the correct version of Python for debugging and linting if possible

**Comment by duxbuse** [comment] 2017-09-07 01:36
I edited the User settings to reference the Python launcher version. So now when I run the script in the terminal or with out the debugger it reacts to the shebangs. But when running with the debugger it reverts to py3 for some reason.

**Comment by DonJayamanne** [comment] 2017-09-07 04:34
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1130

**Closed by DonJayamanne** 2017-09-07 04:34 UTC
