### ISSUE TITLE
Debugger fails to launch: Unexpected token ..vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_launcher.py'

### ISSUE THREAD

**Issue by l4ces** [DonJayamanne/pythonVSCode#1025] opened 2017-06-15 20:39 UTC
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.5
Python Version:   3.6.0
OS and version:    Windows 10 Pro

## Actual behavior
Debugging ceases due to Unexpected token found in vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_launcher.py'

## Expected  behavior
Debugger should execute the script.

## Steps to reproduce:  
-  Load a python script and select debug.
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": null,
            "console": "integratedTerminal",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "externalConsole": false
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/<target-framework>/<project-name.dll>",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```   
Your settings.json:   
```{
    "window.zoomLevel": 2,
    "editor.wordWrap": true,
    "editor.matchBrackets": false,
    "workbench.colorTheme": "Monokai Dimmed",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "workbench.iconTheme": "vscode-great-icons",
    "vim.enableNeovim": false,
    "vim.disableAnnoyingGcMessage": true,
    "vim.disableAnnoyingNeovimMessage": true,
    "editor.renderIndentGuides": false
}
```   
## Logs
Output from ```Python``` output panel  
```
At line:1 char:134
+ ... pythonPath} C:\Users\name\.vscode\extensions\donjayamanne.python- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'C:\Users\name\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_launcher.py' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by abagshaw** [comment] 2017-06-21 19:33
I get the exact same error message, but only when debugging using `Integrated Terminal/Console` when debugging using `Python` everything works just fine.

**Comment by DonJayamanne** [comment] 2017-06-29 11:44
The problem is that the old format of referencing settings from `settings.json` from within the `launch.json` isn't supported anymore. The solution is to merely delete the launch.json and re-create it.
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1047

**Closed by DonJayamanne** 2017-06-29 11:44 UTC
