### ISSUE TITLE
Python intellisense and autocomplete not working as expected.

### ISSUE THREAD

**Issue by mjbvz** [DonJayamanne/pythonVSCode#640] opened 2017-01-12 20:53 UTC
_From @Ogami-Ku on January 12, 2017 20:44_

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 4.4.41-1-lts
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|

---
After installing the extension mentioned above intellisense and autocomplete for python not working as expected. Even pressing "Ctrl+Space" doesn't help. If I want to type "class" and I typed "cl" then pressed "Ctrl+Space"  it keeps "loading..." and nothing happens and I have to delete it then press "Ctrl+Space" or it shows on its own.

![vscode](https://cloud.githubusercontent.com/assets/11742610/21907170/1e380ed6-d917-11e6-8ad1-ac8c0b336fd8.gif)

_Copied from original issue: Microsoft/vscode#18471_

**Comment by DonJayamanne** [comment] 2017-01-12 22:03
Do you have python installed?
If your settings.json configured to point to the python. Interpreter?

**Comment by shawnmcla** [comment] 2017-01-13 06:58
I'm experiencing the exact same issue. I've tried choosing the interpreter through the Python >Select workspace interpreter command as well as explicitly specifying the path to the interpreter in my settings file (python.pythonPath) to no avail. Still getting the "loading.." message indefinitely.

**Comment by Ogami-Ku** [comment] 2017-01-13 08:36
I have python installed yea. It's configured to point to python yea, and I changed the path (python.pythonPath) to /usr/bin/python, /usr/bin/python2, /usr/bin/python3 and /usr/bin/python3.6 then closed Vscode and re-opened it but nothing changed.

**Comment by hanpari** [comment] 2017-01-13 17:25
@DonJayamanne 
I have question. If I write code like this:

```
from multiprocessing import Pool
with Pool(2) as pool:
    pool. ???
```
Am I supposed to get intellisense for pool? Because I dont gat any. I just receiving tooltips for imported modules, no help for functions at all. Is it correct?

I am on Win64 10 with recent VSCode and recent extension.

PS: I tried to set up everything as is indicated here with same result.

**Comment by heyb** [comment] 2017-01-14 02:24
I have same question.
OS Version: Macos 10.12.2
python3 install mode: brew install python3
VSCode Version: Code 1.8.1

**Comment by hirschmann** [comment] 2017-01-14 13:09
Seems to be a problem with python 3.6.

Working:
- python 2.7.13, Windows 10 x64
- python 2.7.13, Linux x64
- python 3.5.2, Linux x64

Not working:
- python 3.6.0, Windows 10 x64

**Comment by dynamo-nath** [comment] 2017-01-14 14:07
Working - 3.5 Windows 10 x64
Working - 2.7.11 Windows 10 x64
Working - 2.7.13 Windows 7 x64

**Comment by Ogami-Ku** [comment] 2017-01-14 14:18
Now that I installed (python3.5.2) and changed the path to it, it's working. The problem is in python3.6.

**Comment by hanpari** [comment] 2017-01-14 16:16
In that case I have bad luck because I have python 3.5.2 :(

**Comment by Rmanolis** [comment] 2017-01-14 16:48
I fixed the problem by creating a new file called grammar3.6.txt
vim ~/.vscode/extensions/donjayamanne.python-0.5.5/pythonFiles/preview/jedi/parser/grammar3.6.txt
and copy pasting this file https://raw.githubusercontent.com/davidhalter/jedi/master/jedi/parser/grammar3.6.txt
The problem, based on the code --verbose was with the jedi. 
At first I got confused because I installed the latest jedi version from github, but then I realised that the plugin has its own jedi application. 
It will be fixed if the owner update to the new jedi for the plugin also.

**Comment by alvarocneto** [comment] 2017-01-15 01:14
@Rmanolis  Thank You !! It works!

**Comment by Agnpalm** [comment] 2017-01-18 14:39
I had this issue too. I just updated to version 0.5.6 of this plugin, and now it works.

**Closed** 2017-01-18 20:20 UTC

**Comment by Odame** [comment] 2017-07-27 12:52
I am experiencing this same issue. The autocompletion works fine, for a while when I start vscode, and then after some time (I have not been able to measure the time, but is in the range of minutes), it stops working.

When I restart vscode or my computer, it still behaves the same way.

@Rmanolis The link you sent is dead

**Comment by houstonian** [comment] 2017-08-13 16:13
I have having a similar problem with Python 3.6.2
VS Code Version 1.15.0 (1.15.0)
Python plug-in 0.7.0

**Comment by jcyamacho** [comment] 2017-10-25 12:22
I am having the same problem
Python 3.6.2
VS Code Version 1.17.2
Python plug-in 0.7.0
Anaconda 5.0.0
win10 x64

**Comment by DonJayamanne** [comment] 2017-10-25 15:40
Please try uninstalling the extension and re-installing the extension.
Also please ensure you have set the path for the python interperter in your workspace or user settings (```settings.json```) under ```python.pythonPath```

See here https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

**Comment by lizy14** [comment] 2017-12-19 06:50
In addition to uninstalling and re-installing the extension, also try disabling and re-enabling the extension.

**Comment by trondhindenes** [comment] 2017-12-31 12:48
I'm having the same problem on Ubuntu 17.10, python 3.6.3. I've tried reinstalling the extension and explicitly setting the python path. I can see the python linter is working (it shows errors after a few seconds of "idle"), but autocomplete is limited to "dumb" completion based on text in the file.

**Comment by linonetwo** [comment] 2018-01-25 02:44
https://code.visualstudio.com/docs/python/environments This works for me, try select python inside your /usr/local/bin

**Comment by kaleb** [comment] 2018-02-12 12:06
I also had this same issue. I have tried both python36 and python37 on ubuntu. I can get it to work when I set python.jediPath. I cannot get right-click->go-to-definition to work however

**Comment by jeffmartinxyz** [comment] 2018-02-17 06:08
Installing and manually setting python.jediPath achieved the same results for me.
