### ISSUE TITLE
Goto definition for some functions are taking to the wrong definitions. 

### ISSUE THREAD

**Issue by nohupped** [DonJayamanne/pythonVSCode#1046] opened 2017-06-23 05:37 UTC
Not sure if this is out of scope of this plugin, and falls under vscode itself, as this was observed with the Goto definition with the command+click.
## Environment data
VS Code version:  Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
Python Extension version:  0.6.5
Python Version:   2.7
OS and version:     Darwin x64 16.6.0

## Actual behavior
Goto definition of function rsync_project is taking to the wrong definition host_prompting_wrapper when using python's fabric.

## Steps to reproduce:  
-  In a python file, add 
```
from fabric.contrib.project import rsync_project
from fabric.api import sudo
```

-  Hover the mouse over `rsync_project` or `sudo` or command+click on it to take to the definition. It goes to the definition for host_prompting_wrapper in a different file instead of the definition for sudo or rsync_project. This is not observed for all functions. This is observed for a very limited set of functions.
<img width="1390" alt="python code navigation" src="https://user-images.githubusercontent.com/8809560/27467893-c6000da0-5818-11e7-8c41-2c2716aa9593.png">
This was observed when using fabric in python.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```
Thank you.

**Comment by jeffgabhart** [comment] 2017-06-23 15:27
#742

**Comment by PeterJCLaw** [comment] 2017-07-15 14:44
Both of the functions you mention are decorated by the `needs_host` decorator (from `fabric.network`). The `host_prompting_wrapper` you're seeing is defined inside that decorator.

As @jeffgabhart noted, I expect this is a duplicate of #742 in the general case and propose closing this issue in favour of that one. Please do join the discussion there!

**Comment by DonJayamanne** [comment] 2017-07-31 11:40
Same as https://github.com/DonJayamanne/pythonVSCode/issues/478

**Closed** 2017-09-25 17:22 UTC
