### ISSUE TITLE
Feature Request: Automatic doc string contents

### ISSUE THREAD

**Issue by thewickedaxe** [DonJayamanne/pythonVSCode#1126] opened 2017-07-27 20:59 UTC
## Environment data
VS Code version:  1.14.2
Python Extension version:  0.6.9
Python Version:   2.7.9
OS and version:    MS Windows 10

## Actual behavior
Hitting """ just creates a normal python string
## Expected  behavior
I'd like to have a feature where it automatically populates stuff like param and return if the string being created is the docstring of a method.
## Steps to reproduce:  
-  Make a method
-  Type """ under the method declaration

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment] 2017-09-13 21:16
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/165

**Closed by DonJayamanne** 2017-09-13 21:16 UTC
Labels: Docstring, enhancement
