### ISSUE TITLE
Completion in debug console

### ISSUE THREAD

**Issue by cryptomaniac512** [DonJayamanne/pythonVSCode#1285] opened 2017-10-09 04:40 UTC
## Environment data
VS Code version:  1.17.0
Python Extension version:  0.7.0
Python Version:   3.6
OS and version:    Linux 4.12.13

Can debugger console provide completion? Now when I call completion in debug console I get "No suggestion".
I think it would be very convenient to have an autocomplete during debugging, otherwise, it's not much more convenient than debugging with a separate debugger.

**Comment by DonJayamanne** [comment] 2017-10-09 04:43
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/661

**Closed by DonJayamanne** 2017-10-09 04:43 UTC
Labels: Debugger, duplicate, enhancement
