### ISSUE TITLE
Look for yapf configuration file

### ISSUE THREAD

**Issue by patrick91** [DonJayamanne/pythonVSCode#799] opened 2017-03-07 12:48 UTC
Hi! I found a use case where I'd need to specify the yapf configuration file manually, since all the other ways won't work.

I have this directory structure

```
project/
-- backend/
---- .style.yapf
```

I usually open the `project`, which means that the workingRoot will be `project`. 
When I run the formatter from VS Code it won't pickup the configuration file inside the `backend` folder. So I'd need to specify the path manually, right now I'm doing this inside the workspace settings, but I think it would be nice if this plugin handled this use case. 
I'm happy to make a PR if you want to have this feature.

The idea is to find the first `.style.yapf` file (starting from the current file path) and pass that as an argument to yapf

**Comment by DonJayamanne** [comment] 2017-03-07 13:23
Where is your file located? Is it inside the ```backend``` directory?

**Comment by DonJayamanne** [comment] 2017-03-07 13:29
The problematic code is here (you may have identified this):
https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/formatters/baseFormatter.ts#L32

In Yapf, all we need to do is change this line to use the directory where the file resides. Yapf will walk up the directory looking for the config file.   
However, autopep8 doesn't mention any such thing, my suggestion, is to parameterize this directory (add a new argument to ```provideDocumentFormattingEdits```). For Yapf this can be the file directory, for autopep8, same as existing logic.

Please feel free to submit a PR.
If your solution was different, I'm happy to listen to that.

**Comment by patrick91** [comment] 2017-03-07 14:06
Yup! The config file is inside backend :)

I was thinking to just change the yapf code, here: https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/formatters/yapfFormatter.ts#L13

I have tried to pass the correct working directory but it didn't work (not even on the command line) maybe it is a bug of YAPF, not sure :)

**Comment by DonJayamanne** [comment] 2017-03-09 13:06
uhm, not sure this will work as expected:
 
> The default _formatting style_ is pep8 unless a
> .style.yapf or setup.cfg file located in one of the
> parent directories of the source file (or current
> directory for stdin)

(from https://github.com/google/yapf#usage)

it will work for saved files, but for unsaved files it probably won't since it will only look in the `cwd` directory, and not going up (from what I have understood). Sorry I haven't tested it yet

**Comment by DonJayamanne** [comment] 2017-10-05 20:48
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/992

**Closed by DonJayamanne** 2017-10-05 20:48 UTC
Labels: Misc
