### ISSUE TITLE
First 'Run selection in Python Terminal' command doesn't execute the command

### ISSUE THREAD

**Issue by hun1ahpu** [DonJayamanne/pythonVSCode#741] opened 2017-02-12 17:06 UTC
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3
OS and version:    win10

## Actual behavior
If the python terminal is not yet started the first 'Run Selection in Python Terminal' command will start it but the actual selected lines will not be executed
![runselectionpython](https://cloud.githubusercontent.com/assets/4397796/22864232/e0017180-f14d-11e6-8ad7-eeb586654d37.gif)

**Comment by DonJayamanne** [comment] 2017-02-12 22:45
Possibly be fixed in the dev version, will keep you posted.

**Comment by DonJayamanne** [comment] 2017-10-31 18:48
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1163
(text sent to terminal even before terminal is able to accept input)

**Closed by DonJayamanne** 2017-10-31 18:48 UTC
Labels: bug, Misc
