### ISSUE TITLE
default launch configurations shows lots of warnings

### ISSUE THREAD

**Issue by weinand** [DonJayamanne/pythonVSCode#873] opened 2017-04-12 08:20 UTC
- VS Code 1.11.1
- Python 0.6.0 extension

![2017-04-12_10-17-13](https://cloud.githubusercontent.com/assets/1898161/24948066/66ae23c4-1f69-11e7-918a-8475906b226b.png)

- to fix the first problem change the variables to use the ':' (instead of '.') as a separator between the category and the variable
- add a 'null' to your json schema in the package.json

**Comment by DonJayamanne** [comment] 2017-04-12 08:44
Thanks for the pointer.
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/774
Fixed

**Closed by DonJayamanne** 2017-04-12 08:44 UTC
