### ISSUE TITLE
Debug output size limit confusing the debugger

### ISSUE THREAD

**Issue by adjames** [DonJayamanne/pythonVSCode#52] opened 2016-03-21 19:07 UTC
First let me say thank you for your awesome Python Extension!

Is there a way to increase the buffer size of the debug console?
If you run this in the debugger:

```
for i in range(0,10000):
	print("line " + str(i))
```

for me the output stops after this:
```
...
line 2566
line 2567
line 2568
line 2569
```

And the debugger claims it can pause, but when you click pause nothing happens, I can understand that the buffer size limit exists, and perhaps my code has completely run. But clearly the fact the output has not been written to the console window is confusing the debuggers somehow.

Three questions. 
- Is there a setting to change the debug output limit? 
- And is this a known issue?  
- Can you detect that the output has not yet occurred?

**Comment by DonJayamanne** [comment] 2016-04-05 09:27
Hi, I have looked at this and I haven't had much luck.
I too can replicate the issue, however the last entry in my debug window is: 
**line 7886**

**Comment by adjames** [comment] 2016-04-07 04:02
No worries. FWIW I'm running on El Capitan. Perhaps the buffer size is different on different platforms?

**Comment by DonJayamanne** [comment] 2016-05-03 13:38
Closing as it doesn't seem to be an issue with the extension.

**Comment by DonJayamanne** [comment] 2016-07-13 03:33
@adjames ,

**Comment by DonJayamanne** [comment] 2016-07-13 03:35
And closing again as this is a duplicate of #203

**Closed** 2016-07-13 03:34 UTC
