### ISSUE TITLE
python extension auto create .vscode folder when I open my project, how can I forbid this

### ISSUE THREAD

**Issue by BrillanceZhang** [DonJayamanne/pythonVSCode#1076] opened 2017-07-11 09:33 UTC
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.7
Python Version:   2.7.13
OS and version:    windows7

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment] 2017-09-25 17:18
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1096

**Closed by DonJayamanne** 2017-09-25 17:18 UTC
