### ISSUE TITLE
MyPy linter not working even when installed

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#505] opened 2016-11-10 02:23 UTC
## Environment data
VS Code version:  1.8.0-insider
Python Extension version:  0.5.1
Python Version: 3.5.2 (Anaconda 4.2.0 64-bit)  
OS and version: Windows 10   

settings.json:   
```
{
    "editor.rulers": [80],

    "python.linting.enabled": true,

    "python.linting.pylintEnabled": true,

    "python.linting.mypyEnabled": true,

    "files.autoSave": "afterDelay"
}
```   
## Logs
Output from ```Python``` output panel  
```
Linting with mypy failed.
You could either install the 'mypy' linter or turn it off in setings.json via "python.linting.mypyEnabled = false".
Error: spawn mypy ENOENT
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
messageService.ts:126Linter mypy is not installede.doShow @ messageService.ts:126
shell.ts:457Unknown location for grammar <testOutput.log>: Error: Unknown location for grammar <testOutput.log>
    at Registry.loadGrammar (C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\node_modules\vscode-textmate\release\main.js:2108:30)
    at e.registerDefinition (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:126:11144)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:126:11016
    at e.invoke (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:22801)
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:31:1364)
    at i.e._getOrCreateMode (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:65:9618)
    at file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:65:8988
    at then (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:32:18377)
    at i.e.getOrCreateMode (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:65:8942)
    at t.getOrCreateMode (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:81:19420)e.onUnexpectedError @ shell.ts:457
languageConfigurationExtensionPoint.ts:61Error: ENOENT: no such file or directory, open 'C:\Users\USERNAME\.vscode-insiders\extensions\donjayamanne.python-0.5.1\src\syntaxes\test.configuration.json'
    at Error (native)(anonymous function) @ languageConfigurationExtensionPoint.ts:61
```

## Actual behavior
Get message that MyPy is not installed:
![image](https://cloud.githubusercontent.com/assets/21064086/20162351/75b18a34-a6c2-11e6-94ec-95ac7164faee.png)

But it is installed:
![image](https://cloud.githubusercontent.com/assets/21064086/20162411/e78548da-a6c2-11e6-8bcc-6a22ebccd20c.png)

## Expected  behavior
MyPy linting to work without any issues

## Steps to reproduce:  
-  Start up VS Code with MyPy linting enabled

**Comment by DonJayamanne** [comment] 2016-11-10 02:45
New version released, with this fix

**Comment by gandhis1** [comment] 2016-11-10 03:33
Please re-open - I still get this behavior in 0.5.2. Anything I should add to this to get some better insight as to why pythonVSCode cannot pick up the MyPy install?

**Comment by DonJayamanne** [comment] 2016-11-10 08:03
Please provide the logs once again

**Comment by moigagoo** [comment] 2016-11-11 12:38
@DonJayamanne I'm having this issue on 0.5.2. Here's the message from the console:
```
messageService.ts:128 Linter mypy is not installed
e.doShow	@	messageService.ts:128
e.show	@	messageService.ts:107
(anonymous function)	@	mainThreadMessageService.ts:55
n.Class.derive._oncancel	@	winjs.base.raw.js:1641
t.$showMessage	@	mainThreadMessageService.ts:25
e.handle	@	abstractThreadService.ts:34
s	@	ipcRemoteCom.ts:269
f	@	ipcRemoteCom.ts:226
_combinedTickCallback	@	internal/process/next_tick.js:67
_tickCallback	@	internal/process/next_tick.js:98

```

**Comment by gandhis1** [comment] 2016-11-22 00:19
Can you re-open this? 

I don't see much in the console output:

`2messageService.ts:126Linter mypy is not installede.doShow @ messageService.ts:126`

**Comment by gediminasz** [comment] 2017-01-20 18:06
On Windows 10 what helped me was specify the exact path to mypy in vscode settings. For example:

```json
"python.linting.mypyPath": "C:\\Users\\yourusername\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\mypy.bat",
```

VS Code 1.8.1
Python extension 0.5.6

**Comment by gandhis1** [comment] 2017-01-20 19:14
I'll give it a try but it would be great if a pip install was all that was needed to get this to work, as it is with pylint/flake8/etc.

**Comment by gandhis1** [comment] 2017-01-24 01:39
Calling MyPy from the command line works, but specifying the path doesn't work either. At least with that, it doesn't prompt to say that MyPy is not installed. Can we re-open this issue, as I'm pretty sure this is a real issue at this point?

**Comment by xeor** [comment] 2017-03-29 09:06
I got the same problem if I use mypy as a linter.
It seams to work tho, if I don't use it as a linter. Example, a simple test like:
```py
a = 'a string'
a.count().
```
shows me the completion from an int-type.

Trying to save and trigger a lint, shows that `mypy is not installed`.

* windows 7
* vscode 1.10.2
* python plugin v0.6.0
* python 3.6.1 (installed via choco)

**Comment by porglezomp** [comment] 2017-06-13 13:49
I can confirm this is still failing, 
Output:
```
Linting with mypy failed.
You could either install the 'mypy' linter or turn it off in setings.json via "python.linting.mypyEnabled = false".
Error: spawn mypy ENOENT
```
Console:
```
Linter mypy is not installed
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1638
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by gandhis1** [comment] 2017-06-13 15:27
I believe the problem only exists when you don't specify the direct path to MyPy.

**Comment by porglezomp** [comment] 2017-06-13 15:38
I had this problem whether or not I specified a direct absolute path to mypy.

**Comment by DonJayamanne** [comment] 2017-07-03 13:21
Should be fixed along with #930 & #998

**Closed by DonJayamanne** 2017-07-03 13:21 UTC

**Comment by lromanov** [comment] 2017-07-08 17:43
@DonJayamanne does version 0.6.7 contain this fix?
If not, when will it be released?
Thanks.

**Comment by DonJayamanne** [comment] 2017-07-09 01:34
Yes it does

**Comment by falan** [comment] 2017-09-01 02:38
I can repeat the problem now.
If I open a single py file without open with folder, the mypy works fine.
If I open with folder, then choose the same file in the folder. It will not show any error.
Hope this helps.

**Comment by lingz** [comment] 2018-09-13 16:16
So the only way I managed to get mypy to work inside vscode was to add a `mypy.ini` file in my root with a mypy_path set to my virtualenv site-packages:

`mypy.ini`

```
[mypy]
mypy_path = env/lib/python3.6/site-packages/:python/
``` 

The last bit is because `python/` is our `PYTHONPATH`
