### ISSUE TITLE
Re-using terminal window for "Run Python File in Terminal" does not create new window if current one is executing

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#419] opened 2016-10-21 15:08 UTC
This is a result of the recent change in v0.5 which re-uses terminals.

Let's say I have a Python file running, using the command "Run Python File in Terminal". If I run a second file using the same approach, it waits for the first to finish. I don't think this is desirable behavior - it should run in a new instance of the terminal, **if the current one is blocking**. Is it possible to know whether the terminal is blocking or not under the current VSCode API?

**Comment by DonJayamanne** [comment] 2016-10-22 02:29
Unfortunately the terminal api wouldn't know if the code is blocking or running (i don't think this is even possible).. The only option is to provide the option to the user.. 
I will provide an option to configure the creation of terminals as follows:
- Always create new terminal. 
- Always reuse terminals (default). 
- Prompt user to decide.

**Comment by dborrett** [comment] 2016-11-23 21:28
Would it not be possible to create associations between a given script (tab) and a terminal instance? So when you start VScode, selecting tab 'foo1.py' and "Run Python File in Terminal", would create a new terminal ('term1') and associate it with 'foo1.py'. From now on 'foo1.py' will always use 'term1' to run in. If I select another tab containing 'foo2.py' and "Run Python File in Terminal", this won't yet have a terminal association and will therefore create a new one with 'term2', say. Then you can switch between the two scripts and run them both at the same time if required in their own terminal.

**Comment by DonJayamanne** [comment] 2016-11-23 22:03
Anything is possible, but the problem is trying to satisfy everyones wants.  
Others may not want the same behaviour.   
How about we wait for some more feed back before we decide on an implementation.

**Comment by gandhis1** [comment] 2016-11-23 22:42
@dborrett I like the idea. That's all I got 👍

**Comment by dborrett** [comment] 2016-11-24 03:16
Yep, good idea to wait for more feedback. I would think that the ability to run more than one script at a time would be a really useful feature for a lot of people though. My suggestion is loosely based on the way PyDev/Eclipse works, though that is quite clunky to use. Keep up the good work Don, it's much appreciated!

**Comment by gandhis1** [comment] 2017-01-18 14:01
There have been some VS Code updates which may have made possible what was previously not:

https://github.com/Microsoft/vscode/pull/18336

**Comment by DonJayamanne** [comment] 2017-01-18 14:31
@gandhis1 , thanks will look into this.

**Comment by DonJayamanne** [comment] 2017-10-18 20:47
Closing as there hasn't been much interest (by others) in this feature

**Closed by DonJayamanne** 2017-10-18 20:47 UTC
Labels: enhancement, Misc
