### ISSUE TITLE
autopep8 doesn't use config in setup.cfg when using `formatOnSave`

### ISSUE THREAD

**Issue by iwinux** [DonJayamanne/pythonVSCode#1034] opened 2017-06-19 07:06 UTC
## Environment data
VS Code version: 1.13.1
Python Extension version: 0.6.5
Python Version: 3.6.1 (installed by `brew install`)
OS and version: 10.12.3

## Actual behavior

autopep8 formats my code without using config from local `setup.cfg`:

```ini
[pep8]
max-line-length = 120
ignore = E201,E202
```

```python
# before save:
{ 'key': 'value' }

# after save:
{'key': 'value'}
```

Meanwhile, executing `autopep8 file.py` in CLI works as expected.

## Expected  behavior

Expected output should be:

```python
# before save:
{ 'key': 'value' }

# after save (no change):
{ 'key': 'value' }
```

## Steps to reproduce:

- create `setup.cfg` in project root
- create a Python file with above content
- save file

## Settings  

Your settings.json:   
```json
{
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.lintOnTextChange": false,
  "python.linting.flake8Path": "/usr/local/bin/flake8",
  "python.formatting.autopep8Path": "/usr/local/bin/autopep8",
  "python.formatting.autopep8Args": ["--verbose"],
  "python.formatting.formatOnSave": true
}
```   

## Logs
Output from ```Python``` output panel (no output from autopep8 even with `--verbose`):

```
##########Linting Output - flake8##########
```   

Output from ```Console window``` (Help->Developer Tools menu): [here](https://gist.github.com/iwinux/df6a54c572a10c49278bfa3638e90ce1)

**Comment by DonJayamanne** [comment] 2017-06-19 08:42
Is your project root the same directory that you have opened up in vscode?

**Comment by iwinux** [comment] 2017-06-19 09:24
@DonJayamanne Yes, they are the same.

Additional info: manually executing command "Format Document" in Command Palette also works as expected. Only the "format on save" feature ignores `setup.cfg` settings.

**Comment by imhuay** [comment] 2017-06-19 14:10
@DonJayamanne the `--ignore` seems doesn't work, please see #1033

**Comment by mike-pt** [comment] 2017-07-07 22:00
I'm seeing setup.cfg ignored even without format on save, in my case I simply have:

```
[pycodestyle]
max-line-length = 120
```

but vscode /pep8 still insists on the 79 char limit

**Comment by PlugaruT** [comment] 2017-10-04 08:06
@mike-pt instead of `[pycodestyle]` write `[pep8]`.

**Comment by mike-pt** [comment] 2017-10-04 12:05
thanks @PlugaruT but that still shows the 79 char limit :|

**Comment by DonJayamanne** [comment] 2017-10-05 20:50
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/992

**Closed by DonJayamanne** 2017-10-05 20:50 UTC
Labels: bug, Format

**Comment by np-8** [comment] 2017-12-19 08:29
I have similar issue. Actually, seems that the autopep8 autoformatting with a `setup.cfg` kind of works if I press `Ctrl+S` multiple times.  I found that with this setting the behaviour is more deterministic: `"python.formatting.autopep8Args": ["--global-config", "${workspaceRoot}/setup.cfg"]`

**Comment by DollarAkshay** [comment] 2018-03-03 16:12
@np-8 Thanks a lot. That seemed to have helped me fix the bug in VS Code
