### ISSUE TITLE
Debugger: <string> is not available.

### ISSUE THREAD

**Issue by db4** [DonJayamanne/pythonVSCode#237] opened 2016-08-02 05:53 UTC
While debugging a program and stepping into a function I see
```
Source C:\Work\opencv-py\<string> is not available.
```
in the new editor tab labeled `<string>`. The stack is the following:

![image](https://cloud.githubusercontent.com/assets/6112699/17318312/1ece18ea-588e-11e6-8b79-ce0bebfc661a.png)
I suppose the debugger cannot find something, but what?

**Comment by DonJayamanne** [comment] 2016-08-02 23:09
@db4 , would it be possible to provide the sample code to replicate this.
It looks like a stackframe has been reached for which the source isn't available or wasn't identified correctly.

**Comment by mww012** [comment] 2016-08-03 18:44
I'm seeing this as well.  For me, it's as simple as trying to import paramiko(installed by pip).  I am running in a venv and everything else seems good except for the debugging.  VSCode 1.3.1 and python ext is 0.3.1.8.  Can get more info if needed but don't want to hijack this ticket since @db4 started it.

**Comment by DonJayamanne** [comment] 2016-08-03 22:11
@mww012 , I don't think you'd be hijacking anything. The more information you provide, that'll help both @db4 as well as my self.

**Comment by db4** [comment] 2016-08-04 05:25
Well, you can replicate it with `Pillow` tests: clone https://github.com/python-pillow/Pillow and debug `Tests/test_file_tiff.py`, setting breakpoint on line 209:
```
im.seek(n_frames)
```
Then try to step into and you should see the problem.

**Comment by mww012** [comment] 2016-08-04 14:11
For me it's the actual line `import paramiko` in VSCode.  From pyCharm or just jumping into the venv in powershell works fine.  On that note, it only seems to be happening on Win10 for me.  I tried to replicate as closely as I could (venv, software version, etc.) on my Mac and don't see the issue.  Any other info I can get that would help?

**Comment by DonJayamanne** [comment] 2016-08-08 00:17
@db4 , I've tried installing the dependencies of Pillow, however i'm getting the following error:
```
Command "/Users/<.....>/Thirdparty/Pillow/devPy/bin/python -c "import setuptools, tokeniz
e;__file__='/Users/<.....>/Thirdparty/Pillow/setup.py';exec(compile(getattr(tokenize, 'op
en', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Us
ers/<.....>/Thirdparty/Pillow/  
```

Any idea what this could be?

**Comment by DonJayamanne** [comment] 2016-08-08 00:17
@mww012, will try your approach

**Comment by DonJayamanne** [comment] 2016-08-08 00:34
@mww012 , what version of python are you using. I've tested this on Windows 10, with Python 3.5 and the following code, however with no luck.

```python
import paramiko
print("hello")
```

**Comment by DonJayamanne** [comment] 2016-08-08 00:47
@mww012 , bingo, managed to replicate this on py2.7 with windows10

**Comment by DonJayamanne** [comment] 2016-08-08 01:18
@mww012 , @db4 , the fix will be in the next release guys. Thanks for your help identifying the root cause.

**Comment by mww012** [comment] 2016-08-08 01:41
Awesome!  Glad you found the root cause. Much appreciated.

**Comment by db4** [comment] 2016-08-08 11:48
> bingo, managed to replicate this on python 2.7 with windows10

For me It still does not work as expected (as it does with PyDev/Eclipse on the same machine). FYI, I use Python 3.5.1 on Windows 10. When I try to step into `seek()`, I have the following stack:

![image](https://cloud.githubusercontent.com/assets/6112699/17478570/84ee8cf4-5d75-11e6-9f4d-02b009a4ed8c.png)

The debugger does not stop immediately after entering `seek()` but runs until "Unknown Source".

As for your problem with Pillow dependencies - I installed Pillow via `pip` and then cloned its git repo to play with its test cases.

**Comment by DonJayamanne** [comment] 2016-08-08 21:40
@db4, the fix has not yet been released, do you won't (unfortunately) have it yet. I will publish a new version next week if that's fine with you. I could also give you the necessary files tho fix it at your end.

**Comment by DonJayamanne** [comment] 2016-08-08 21:41
Oops, closing

**Closed by DonJayamanne** 2016-08-08 21:41 UTC

**Comment by db4** [comment] 2016-08-09 03:42
> @db4, the fix has not yet been released, do you won't (unfortunately) have it yet.

I do have it. I have build and packaged your master branch to try the fix.
