### ISSUE TITLE
Inspecting default parameter values highlights parameter but gives information on the entire function prototype

### ISSUE THREAD

**Issue by Tyriar** [DonJayamanne/pythonVSCode#435] opened 2016-10-26 18:26 UTC
![image](https://cloud.githubusercontent.com/assets/2193314/19739114/9a79a856-9b6e-11e6-8b74-6836126ae860.png)

I'm expecting a peek at its definition as in TypeScript:

![image](https://cloud.githubusercontent.com/assets/2193314/19739227/f945c2fc-9b6e-11e6-8bb4-26a978a9e833.png)

**Comment by DonJayamanne** [comment] 2016-10-26 22:49
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/457

**Closed by DonJayamanne** 2016-10-26 22:49 UTC
