### ISSUE TITLE
Idea: allow searching in "~/.virtualenvs" for virtual environments

### ISSUE THREAD

**Issue by ncoghlan** [DonJayamanne/pythonVSCode#569] opened 2016-12-08 03:23 UTC
I use `vex` to manage my virtual environments, and it collects them all in `~/.virtualenvs` by default rather than putting them in the individual project working directories. Other tools like `virtualenvwrapper` similarly let users specify a storage directory via the `WORKON_HOME` environment variable.

It wouldn't make sense to teach VSCode about all the different ways folks may configure their venv management, but it *might* make sense to provide a configuration option to override the current "search in the workspace root" behaviour at https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/setInterpreterProvider.ts#L193

The approach I am thinking of submitting is to add a new config setting:

    "python.venvPath": ""

If it's not set, then the plugin would use the existing logic of searching in the workspace root directory. If it *is* set, then it would search that location instead of the workspace root.

If that approach sounds reasonable, then I'll put a PR together implementing it.

**Comment by gmeans** [comment] 2016-12-08 21:28
Just came here looking for the same feature. I think what you are proposing sounds great.

**Comment by prashnts** [comment] 2016-12-15 09:12
I use this different approach -- writ a proxy executable and put it in your path, and use it to find the correct interpreter for your venv.

Assumptions:
- The virtualenv is named the same as the project dir (common, as `autoenv` etc. use the same approach).
- It's a git project (optional, makes it faster to search for the project root).

Then, we can use something like the following to proxy finding the correct binary for us. As an added benefit, it can also source `.env` file, if exists -- so your configuration remains same.

From my dotfiles:
https://github.com/prashnts/dotfiles/blob/master/bin/python-venv
```bash
#!/usr/bin/env bash
GIT_TOPLEVEL=`git rev-parse --show-toplevel 2> /dev/null`
GIT_DIRNAME=`echo $GIT_TOPLEVEL | rev | cut -d'/' -f1 | rev`
if [[ -s "$GIT_TOPLEVEL/.env" ]]; then
  source $GIT_TOPLEVEL/.env
fi
export PYENV_VERSION=$GIT_DIRNAME
~/.pyenv/shims/python $@
```

I've put this in my `PATH`, and in `launch.json`, it is:
```json
      "pythonPath": "python-venv",
```

Hope this might be useful.

**Comment by eromoe** [comment] 2016-12-29 06:42
I think the folder name should be configable. I am using virtualenvwrapper-win , which would create `~/Envs` folder instead of `~/.virtualenvs`.

**Comment by marcosfede** [comment] 2017-01-11 02:26
I use pyenv which saves virtualenvs on ~/.pyenv   by default. please add a feature to configure the virtualenv default directory

**Comment by ncoghlan** [comment] 2017-02-23 13:03
@DonJayamanne Thank you!

**Comment by heww** [comment] 2017-03-03 02:07
@DonJayamanne i test this on mac, it does not work when i set `python.venvPath` to `~/.virtualenvs`, the fix only search dirs`python.venvPath` on Window, but not mac and linux.

**Comment by DonJayamanne** [comment] 2017-03-03 12:45
Yes, it does search for Mac and linux as well.
https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/setInterpreterProvider.ts#L76

Also, /.virtualenvs has been added as a default search location for Macs and Linux:
https://github.com/DonJayamanne/pythonVSCode/blob/master/src/client/providers/setInterpreterProvider.ts#L70

**Comment by marcosfede** [comment] 2017-03-12 23:10
should the virtualenv interpreters appear on the "select interpreter" dropdown? It seems that its not working right now on mac or Linux, even if I set python.venvPath to my virtualenv directory the interpreter doesn't appear on the dropdown, and the extension keeps asking me to install pep8 and such even though I have them installed on the active python version I'm using (through pyenv), so the system python is being used.
I even tried selecting python.pythonPath as "~/.pyenv/shims/python" but that doesn't work either. does anyone know how to set this up to work with pyenv ?

**Comment by ncoghlan** [comment] 2017-03-21 07:12
After updating to the latest version of the plugin, I can confirm I still appear to only be getting the system wide copies of Python in the "Select Workspace Interpreter" list.

However, I personally ended up relying on the existing `.venv` directory support to let VSCode know which venv to use: 

    $ echo .venv >> .gitignore
    $ ln -s `dirname $(dirname $(vex cpicker which python))` .venv

That seems to work well enough to at least let pylint know which version of Python syntax it should be checking (2 or 3) and which modules are available for import.

(I realised this would work while experimenting with `pipenv`, which has a dedicated `pipenv --venv` command to get the absolute path to the venv directory)

**Comment by ncoghlan** [comment] 2017-03-21 07:39
My apologies, I take that back - I *thought* it was working, but I was fooled by the "files are only scanned when edited-and-saved" behaviour.

**Comment by xlevus** [comment] 2017-03-22 16:11
Can confirm,

The only way I seem to be able to get virtualenv's working in linux is by placing the virtualenv in `.venv` in the workspace root (or symlinking it elsewhere).

**Comment by ncoghlan** [comment] 2017-03-23 06:26
After further investigation, the remaining problems with the `.venv` based setup were due to some leftover incorrect entries in my workspace settings from earlier attempts to get things working.

**Comment by zkanda** [comment] 2017-03-29 10:56
Doesn't work for me as well. There's a propose fix here: https://github.com/DonJayamanne/pythonVSCode/pull/815

**Comment by DonJayamanne** [comment] 2017-04-27 12:11
Please retest, I believe the merged fix (#815) fixes this issue. If not please reopen

**Comment by zkanda** [comment] 2017-04-28 04:11
@DonJayamanne can you release a new version? :+1: 
Cheers!

**Comment by DonJayamanne** [comment] 2017-04-28 05:15
Oops, will release a version.

**Comment by ssword** [comment] 2017-05-03 06:36
I think "~/.virtualenvs", "~/Envs" are more commonly used than "/.virtualenvs" and "/Envs". In #815, it is using the latter two.

**Comment by mrmachine** [comment] 2017-05-04 04:49
Can I use the develop version somehow while we wait for the next release version?

Also, I *think* that `~/.pyenv/versions` should be used instead of `~/.pyenv`. Has anyone tested this with pyenv yet? I'd be happy to, if I knew how to run the develop version of this extension.

I didn't quite understand the contributing docs in the wiki. I'm very new to VS Code.

**Comment by richardadalton** [comment] 2017-05-04 07:46
Hi,

Testing this on a Mac now.
 I have version 0.6.3 of the extension.

I've tried this in both User Settings and Workspace settings, with and without a trailing slash.
"python.venvPath": "~/.virtualenvs"

But I can confirm I'm not seeing the virtualenvs that are there on Mac.

**Comment by richardadalton** [comment] 2017-05-05 10:10
Hi Don,
I just installed 0.6.4 on the Mac, and I still don't see any of the venvs that are in ~/.virtualenvs
I tried with and without setting the python.venvPath setting.

I only see interpreters in usr/bin and usr/local/bin 

It there's anything you'd like me to test let me know.

**Comment by DonJayamanne** [comment] 2017-05-05 12:30
Sorry, didn't test the damn thing, was too confident... :(

**Comment by richardadalton** [comment] 2017-05-05 13:47
I'm probably not doing this right, I haven't ever worked on VSCode extensions, but I seem to have it up and running in the Extension Development Host, and I tried hard-coding the ~/.virtualenvs path in that setInterpreterProfider.ts file, just to see if that would work, and it still doesn't work.

Like I say, probably something I'm doing wrong. I'd like to get my head around it to help out. It's a great extension.

**Comment by DonJayamanne** [comment] 2017-05-05 13:50
How have you run in ```Extension Development Host```, please could you describe this process.  
I have tested the latest changes locally and it should now work, however you'll need to wait for the release or you can test the dev version.

**Comment by richardadalton** [comment] 2017-05-05 13:54
From what I can see the paths.forEach on line 73 isn't working, as in I can't see it doing the pushes, and if I add
paths.push('~/.virtualenvs');
before the return it doesn't have any effect.

**Comment by richardadalton** [comment] 2017-05-05 13:55
I've git cloned your repo, 
cd into the folder.
npm install
code .
In debug tab I ran Launch Extension

**Comment by DonJayamanne** [comment] 2017-05-05 14:02
You need to translate the ```~``` (tild).  
If you look at the code (see below), this translation takes place suing the ```untiltyfy``` function:  
```javascript
paths.push(untildify('~' + p));
```

**Comment by richardadalton** [comment] 2017-05-05 14:07
Ah, good point. I'll try that. 
Interestingly, the path IS in the paths list. And even without a tilde it's valid. See where the mouse pointer is here.


![img_1446](https://cloud.githubusercontent.com/assets/453418/25748863/95b5ee0c-31a4-11e7-9f90-d714001ad89f.JPG)

**Comment by chocoelho** [comment] 2017-05-06 23:57
Is this working? I can't find my virtualenv environments even when manually editing the extension to apply 6eb1f26.

**Comment by valrus** [comment] 2017-05-13 22:14
For anyone else having trouble with this: on Mac (with pyenv and `"python.venvPath": "~/.pyenv/versions"`) all I got in the `Python: Select Workspace Interpreter` was the system pythons. Based on [this comment](https://github.com/DonJayamanne/pythonVSCode/issues/569#issuecomment-299472772) I untildified the path myself (i.e. replaced the `~` with `/Users/<myusername>` and that worked.

**Comment by richardadalton** [comment] 2017-05-14 23:06
Yep, that does the trick. Good thinking.

**Comment by jarshwah** [comment] 2017-06-14 22:18
@DonJayamanne should this one be reopened? The `python.venvPath` only works for me when using an absolute path. The untildify doesn't seem to work.

Apologies if there's a separate issue tracking this.

![relative-home](https://user-images.githubusercontent.com/541083/27157043-2009cfb0-51a3-11e7-9c42-b70362961904.png)
![absolute](https://user-images.githubusercontent.com/541083/27157047-2367f074-51a3-11e7-9ede-b2d5b030457c.png)

**Comment by jroimartin** [comment] 2017-06-21 07:34
PR #1040 should fix this. Can you check? Feedback is welcome :)

**Comment by DonJayamanne** [comment] 2017-06-29 12:51
PR has been merged

**Closed by DonJayamanne** 2017-06-29 12:51 UTC
