### ISSUE TITLE
Cannot run Python Debugger with bash.exe

### ISSUE THREAD

**Issue by dlorch** [DonJayamanne/pythonVSCode#594] opened 2016-12-19 20:48 UTC
## Environment data
VS Code version:  1.5.3
Python Extension version:  0.3.23
Python Version:  3.5.2
OS and version:    Windows 7 Enterprise
Your launch.json (if dealing with debugger issues):  
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": false,
			"program": "${file}",
			"console": "integratedTerminal",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			]
		}
	]
}
```   
Your settings.json:   
```json
{
    "terminal.integrated.shell.windows": "C:/Program Files/cmder/vendor/git-for-windows/bin/bash.exe"
}
```   
## Logs
Output from ```Python``` output panel  
```
DANIEL@MYPC /c/Users/daniel/Documents/Python/testproj                                                                                                       
λ cd c:\Users\daniel\Documents\Python\testproj && cmd /C "python C:\Users\daniel\.vscode\extensions\donjayamanne.python-0.3.23\pythonFiles\PythonTools\visualstudio_py_launcher.py c:\Users\daniel\Documents\Python\testproj 53129 34806ad9-833a-4524-8cd6-18ca4aa74f14 WaitOnAbnormalExit,WaitOnNormalExit c:\Users\daniel\Documents\Python\testproj\hello.py "
bash: cd: c:UsersdanielDocumentsPythontestproj: No such file or directory
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior

Expect python debugger to run

## Expected  behavior

With bash.exe selected as shell, the backslashes in the workdir path are interpreted as escape characters. Maybe the "\\" should be replaced by "/" before cd-ing to the workdir?

## Steps to reproduce:  
-  Install http://cmder.net/
-  Set integrated shell to bash.exe (bundled with cmder)
-  Debug Python program

**Comment by DonJayamanne** [comment] 2016-12-27 05:41
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/534

**Closed by DonJayamanne** 2016-12-27 05:41 UTC
Labels: Debugger, duplicate, enhancement
