### ISSUE TITLE
Some error when formatting code

### ISSUE THREAD

**Issue by XianwuLin** [DonJayamanne/pythonVSCode#187] opened 2016-06-28 02:32 UTC
>Error: There was an error in formatting the document. View the Python output window for details.
 at AutoPep8Formatter.BaseFormatter.handleError (C:\Users\Victor\.vscode\extensions\donjayamanne.python0.3.14\out\client\
formatters\baseFormatter.js:53:15)
 at C:\Users\Victor\.vscode\extensions\donjayamanne.python0.3.14\ out\client\formatters\baseFormatter.js:36:19
 at process._tickCallback (internal/process/next_tick.js:103:7)

![](http://i2.piimg.com/567571/414653bcff57abe0.png)

**vs code version: 1.2.1**
**os: windows 7 x64**

there is my vs code settings.json:
```json
// Place your settings in this file to overwrite the default settings
{
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.renderWhitespace": true,
    "draw_white_space": "all",
    "editor.wrappingColumn": 0,
    "http.proxy": "http://127.0.0.1:7887",
    "python.pythonPath": "c:/python27/python.exe",
    "indent_size": 4,
    "indent_char": " ",
    "css": {
        "indent_size": 2
    },
    "guides.normal.width": "1pt",
    "guides.normal.style": "solid",
    "guides.normal.color": "rgba(255, 255, 255, 0.2)",
    "guides.active.enabled": true,
    "launcher.terminal": {
        "executable": "cmder.exe",
        "parameters": "/start %item_path%"
    },
    "editor.rulers": [
        120
    ],
    "python.linting.pylintArgs": ["--load-plugins", "pylint_django", "--rcfile", "G:\\pylintrc"],
    "python.formatting.provider": "autopep8",
    "files.exclude": {
        "**/*.pyc": true
    }
}
```

**Comment by DonJayamanne** [comment] 2016-06-28 02:50
Hi @XianwuLin , please could you provide the contents of the Python output window.

**Comment by XianwuLin** [comment] 2016-06-28 02:52
@DonJayamanne, where is python output window?

**Comment by DonJayamanne** [comment] 2016-06-28 02:53
Go into "View -> Toggle Output"
Then from the list of the windows, select "Python"
The default output window will be "Tasks"

**Comment by XianwuLin** [comment] 2016-06-28 02:57
![](http://i1.piimg.com/567571/3f99020d235d33b5.png)

**Comment by DonJayamanne** [comment] 2016-06-28 02:59
Hi, the problem is with the formatter. This will be fixed in tonights update.
I will close this issue as it is a duplicate of #181

**Closed by DonJayamanne** 2016-06-28 02:59 UTC
