### ISSUE TITLE
vscode pylint bug

### ISSUE THREAD

**Issue by mjbvz** [DonJayamanne/pythonVSCode#923] opened 2017-04-28 05:49 UTC
_From @SuperSuperSuperSuper5 on April 28, 2017 2:6_

- VSCode Version: 1.112
- OS Version: ubuntu 16.04

Steps to Reproduce:

1.open a python project
2.vscode show you `Error Linter pylint is not installed`
3.then I use the `pip install pylint` and it sucess
4.when I open a python project again, and it show same error massage `Error Linter pylint is not installed`
5.ok, install the pylint again, and it show`Requirement already satisfied`
6.reboot the system and open a python project again, also the same `Error Linter pylint is not installed`

I think it's a vscode bug, THX for developer to fix this problem

_Copied from original issue: Microsoft/vscode#25597_

**Comment by DonJayamanne** [comment] 2017-04-28 06:13
@SuperSuperSuperSuper5
- Please could you provide your workspace settings.json file.  
- Do you use a virtual environment?

**Comment by SuperSuperSuperSuper5** [comment] 2017-04-28 07:19
@DonJayamanne 

* After I do the `Reproduce` which I write above
* There is no settings.json file
* Then the error message show again, vscode want to me install the pylint, and i click the disabled the pylint
* Ok, I get the a vscode dir, and there have a settings.json file

```
{
    "python.linting.pylintEnabled": false
}
```

**Comment by SuperSuperSuperSuper5** [comment] 2017-04-28 07:24
@DonJayamanne I didn't use the virtual environment. This is computer is my old computer which buy in 2013 and I use it to write code.

THX for you to help me.😜

**Comment by iFreilicht** [comment] 2017-06-19 15:59
I have the same issue, or at least it sounds like I do, and it seems like it can be fixed:

## Setup and error explanation

I've set up a venv in a folder inside my project root, which is mounted using `sshfs`.

settings.json:

```
{
    "python.linting.pylintEnabled": true,
    "python.pythonPath": "venv_python3/bin/python"
}
```
When saving a python file, the Error "Linter pylint is not installed" pops up. Clicking on "Install pylint" leads to the following command being executed and output in the internal terminal:

```
$ /<fakepath>/v
env_python3/bin/python -m pip install --upgrade pylint
Requirement already up-to-date: pylint in ./venv_python3/lib/python3.4/site-packages
Cleaning up...
```

So first I thought that pythonVSCode might try to run my global install of pylint, which doesn't exist:

```
$ pylint
zsh: command not found: pylint
```

Ok, that might be an option. But, pythonVSCode is running the correct installation of pip, so that didn't seem right.

Second, I tried to manually run pylint from within the venv, which threw the following error:

```
$ ./venv_python3/bin/pylint --version
zsh: ./venv_python3/bin/pylint: bad interpreter: /<fakepath2>/: no such file or directory
```

So I checked the shebang of `./venv_python3/bin/pylint` and found something:

```
$ head -1 ./venv_python3/bin/pylint
#!/<fakepath2>/venv_python3/bin/python3
```

As the virtual environment was setup on the machine I'm ssh-ing to, that explains why zsh throws a bad interpreter error.

Now, you can also run pylint in the venv like this, which works perfectly fine.

```
$ ./venv_python3/bin/python -m pylint --version
__main__.py 1.7.1,
astroid 1.5.2
Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4]
```

So it seems to me like pythonVSCode is trying to run pylint using the first method, and is then catching the "bad interpreter" error just like it does a "command not found" error.

## Proposed fix:

At the very least, pythonVSCode should forward messages with unknown error codes (like "bad interpreter" in this case) to the error prompt and only display an explanation for known error codes (as it does with "Linter pylint is not installed"). This would make troubleshooting of issues like this easier in the future.

I would argue that pythonVSCode should also call pylint using `$ <venv_path>/bin/python -m pylint` instead of using `$ <venv_path>/bin/pylint`. While the latter is technically just as correct from a logical standpoint, it has been demonstrated that the it is less reliable and can lead to unexpected error messages.

If possible, using `$ <venv_path>/bin/python -m <command>` to call a python command should be a made a general guideline for this repository. This would make the software more robust and the code more consistent.

What are your thoughts, @DonJayamanne?

**Comment by iFreilicht** [comment] 2017-06-21 11:29
Ok, I've looked into it a bit more.

First off, I need to apologize. pythonVSCode does indeed check the error code before claiming that pylint is not installed. The issue is that the two errors `bad interpreter` and `command not found` have the same error code of 127, presumably because the shell will just try to call the interpreter in the shebang line (which doesn't exist), and forward the exit code but prints a custom error message. So to differentiate, the error message needs to be checked in the function `isNotInstalledError(error: Error): boolean` as well.

I also found a workaround for now. In your `settings.json`, add these options:

```json
    "python.pythonPath": "<venv_path>/bin/python",
    "python.linting.pylintPath": "python",
    "python.linting.pylintArgs": [
        "-m",
        "pylint"
    ]
```
This implements the fix that I outlined in my previous comment. The function that needs to be modified to implement it stock would be `runLinter(document: TextDocument, cancellation: CancellationToken): Promise<baseLinter.ILintMessage[]>`, but it seems that this would require a revision of the way linting options are layed out.

Under this light, and also considering that this is quite a niche issue, I would revise my proposal from last post:

## Updated proposal for fix:

Change behaviour of the functions `handleError(expectedFileName: string, fileName: string, error: Error)` in `baseLinter.ts` and `isNotInstalledError(error: Error): boolean` in `helpers.ts` to check the error message for `'bad interpreter'`, and guide the user to the workaround I outlined above.

**Comment by DonJayamanne** [comment] 2017-10-03 23:08
@SuperSuperSuperSuper5 please feel free to reopen the issue if it persists.

**Closed by DonJayamanne** 2017-10-03 23:08 UTC
