### ISSUE TITLE
Indentation on new line in function arguments

### ISSUE THREAD

**Issue by sebastjaeger** [DonJayamanne/pythonVSCode#982] opened 2017-05-24 21:13 UTC
## Environment data
VS Code version:  1.12.2
Python Extension version:  0.6.4
Python Version:  3.6.1
OS and version:  MacOS 10.12.4

## Actual behavior
When hitting enter to start a new line within the arguments of a function, the cursor jumps to the beginning of the def statement on the new line:
```
def foo(bar,
|
```
`|` represents the cursor.

## Expected  behavior
Indent the new line up to the beginning of the arguments of the function:
```
def foo(bar,
        |
```

**Comment by gandhis1** [comment] 2017-05-24 21:28
Duplicate of #306

**Closed** 2017-05-25 00:23 UTC
