### ISSUE TITLE
Docstring always changes ':' to '*'

### ISSUE THREAD

**Issue by SteadBytes** [DonJayamanne/pythonVSCode#1201] opened 2017-09-09 16:11 UTC
## Environment data
VS Code version:  1.16.0
Python Extension version:  0.7.0
Python Version:   3.6.0
OS and version:    Windows 10 Pro 64-bit

## Actual behavior
Colon ':' character in docstrings is always treated as a  '*' even when escaped with '\\'
### Without escaping:

![2017-09-09 3](https://user-images.githubusercontent.com/14834132/30241730-0f17889c-9581-11e7-9632-7ec7b0dcda5b.png)
### With escaping:

![2017-09-09 6](https://user-images.githubusercontent.com/14834132/30241741-6d78867a-9581-11e7-8981-0c721d04f54a.png)

### Within backtick '`'  block
![2017-09-09 10](https://user-images.githubusercontent.com/14834132/30241761-bdc63b36-9581-11e7-96a1-e39a69a123c1.png)

## Expected  behavior
Escaping the ':' will leave allow it to be used or within backtick '`' code blocks
## Steps to reproduce:  
-  Write a docstring for a function using colons - for example to describe the format of a dict:
```Python
def dijkstra(graph, source):
    """ Runs dijkstras algorithm on a weighted graph to create optimal paths
    between nodes

    Args:
        graph (dict) - Graph in the form {node1 : {neighbour1 : weight, 
        neighbour2 : weight}, node2 :{} ...}

        source - key of the source node in
    """
```

**Comment by DonJayamanne** [comment] 2017-09-13 18:33
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1188

**Closed by DonJayamanne** 2017-09-13 18:33 UTC
Labels: bug, duplicate
