### ISSUE TITLE
Intellisence for python not working..

### ISSUE THREAD

**Issue by pkappos** [DonJayamanne/pythonVSCode#613] opened 2016-12-30 09:20 UTC
I have installed python extensions for VS Code, i also put python interpreter to my project. Console output works fine but intellisence not. Any ideas??
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    
Your launch.json (if dealing with debugger issues):  
```json
```   "configurations": [

        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
Your settings.json:   
```json 
```  {
    "python.pythonPath": "C:/Python/python.exe"
}

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior

## Expected  behavior

## Steps to reproduce:  
-  
-

**Comment by playniuniu** [comment] 2016-12-30 13:19
I think this problem is same as https://github.com/DonJayamanne/pythonVSCode/issues/601

The solution is at that thread

just copied grammar3.5.txt to grammar3.6.txt in ~.vscode-insiders\extensions\donjayamanne.python-0.5.5\pythonFiles\preview\jedi\parser and autocompetion worked again

**Comment by ehartford** [comment] 2017-01-04 01:42
I have same problem.
I set python.pythonPath to my interpreter, and python.autoComplete.extraPaths to include all my modules

**Comment by Satak** [comment] 2017-01-04 16:02
Same problem, Python 3.6, Win 10, no intellisense. Is there a fixing coming because I don't want to use any workarounds that can cause problems in the future.

**Comment by DonJayamanne** [comment] 2017-01-05 17:49
@pkappos, what's the information for this? 
VS Code version:
Python Extension version:
Python Version:
OS and version:

**Comment by DonJayamanne** [comment] 2017-01-05 17:50
Ooops

**Comment by DonJayamanne** [comment] 2017-01-16 10:46
Duplicate of #646

**Closed by DonJayamanne** 2017-01-16 10:46 UTC
