### ISSUE TITLE
Unable to import (pylint). All solutions do not work.

### ISSUE THREAD

**Issue by technoiswatchingyou** [DonJayamanne/pythonVSCode#1326] opened 2017-10-19 05:13 UTC
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.7.0
Python Version:   3.6.3
OS and version:   MacOS 10.13.2 

## Actual behavior
E0401: Unable to import 'django.http'
E0401: Unable to import 'django.conf.urls'

## Expected  behavior
Everything needs to be fine

## Steps to reproduce:  
Create simple Django project with any app.

## Logs

##########Linting Output - pylint##########
************* Module webapp.views
7,0,convention,C0304:Final newline missing
1,0,convention,C0111:Missing module docstring
1,0,error,E0401:Unable to import 'django.shortcuts'
2,0,error,E0401:Unable to import 'django.http'
6,0,convention,C0111:Missing function docstring
6,10,warning,W0613:Unused argument 'request'
1,0,warning,W0611:Unused render imported from django.shortcuts

----------------------------------------------------------------------
Your code has been rated at -27.50/10 (previous run: -27.50/10, +0.00)

No config file found, using default configuration

**Comment by DonJayamanne** [comment] 2017-10-19 06:11
What is your settings.Json like.  
where is pythin installed (full. Path)
Finally where is pylint and Django installed.

The problem is you either haven't configured vscode to point to the right interpreter or pylint isn't installed in the same environment as Django.

**Comment by technoiswatchingyou** [comment] 2017-10-19 06:52
jSON: "python.pythonPath": "/usr/local/bin/python3.6",

Pylint installed: /Library/Frameworks/Python.framework/Versions/3.6/bin/pylint

pylint in ./virtenv/lib/python3.6/site-packages
Django in ./virtenv/lib/python3.6/site-packages
pytz in ./virtenv/lib/python3.6/site-packages (from Django)

**Comment by DonJayamanne** [comment] 2017-10-19 16:09
Simple fix:
Modify your json as follows such that ```pythonPath``` points to the python interpreter in your virtual environment  (``` ./virtenv/lib/python3.6/site-packages```)

Please ensure you use the fully qualified path to the interpreter, such as:  
```<fully qualifieid path>/virtenv/bin/python```

**Comment by technoiswatchingyou** [comment] 2017-10-19 23:07
I tried this and nothing changed: 

"python.pythonPath": "./virtenv/bin/python3",

or

"python.pythonPath": "./virtenv/lib/python3.6/site-packages",

**Comment by DonJayamanne** [comment] 2017-10-21 02:04
Please provide the following qualified party to the interpreter.
Can you confirm pylint is installed in the about environment.

Go into the terminal, and get the full list to the python interpreter ```sys.executable```

From the info you provided, it wasn't interested in the same environment.

**Comment by DonJayamanne** [comment] 2017-10-21 02:04
>Also, am i need to configue my .JSON for every new project?

No, you can specify this in your user settings file if you wish.

**Comment by technoiswatchingyou** [comment] 2017-10-25 04:21
@DonJayamanne Ok. So i did what you said an situation is the same. Pylint is installed 100%.

    "python.pythonPath": "/Users/andreymarchenko/Tutorials/mysite/virtenv/lib/python3.6/site-packages",

**Comment by technoiswatchingyou** [comment] 2017-10-25 10:23
@DonJayamanne mate, think that i finally got!

For other folks: You should run "which python" command in Terminal when your virtual environment activated. Than you need to insert this path to "python.pythonPath": "" in VSCode's Settings.JSON. Also pylint should be installed for this path (VSCode will offer you to do this thing). 

But i still can't realize this thing - From what i see i need to use only this virtenv for all my projects? Because if not i need to change "python.pythonPath" everytime?

**Comment by DonJayamanne** [comment] 2017-10-25 15:42
>But i still can't realize this thing - From what i see i need to use only this virtenv for all my projects? Because if not i need to change "python.pythonPath" everytime?  

As mentioned [earlier](https://github.com/DonJayamanne/pythonVSCode/issues/1326#issuecomment-338356780), you can set this setting in your user settings file (i.e. globally, so you don't have to set this everytime).

Closing as you have now managed to get this working.

**Closed by DonJayamanne** 2017-10-25 15:42 UTC
Labels: Linter

**Comment by gopaltirupur** [comment] 2018-04-26 13:16
check correct setting of   "python.linting.pylintArgs" - example given below

 "python.linting.pylintArgs": [           
            "--load-plugins", 
            "pylint_django"
        ]

**Comment by xobs** [comment] 2018-06-17 11:34
I'm still unable to get this to work.

My Python interpreter is C:\Python36\python.exe.  I want to add D:\Code\deps to my path.  If I set `python.pythonPath` to `D:\\Code\\deps` then it complains that my Python environment isn't set.  If I set my Python environment, then `python.pythonPath` gets overwritten.

How can I set `PYTHONPATH` so that `pylint` will work?

**Comment by Kogam22** [comment] 2018-06-19 05:30
@xobs 
Might Try The `PATH` Like This : 
`"python.pythonPath" : "D:\\Code\\deps\\"`

**Comment by clarkkarenl** [comment] 2018-07-07 21:42
I was having this same issue - confirmed all of my venv settings were correct and working. The pylintArgs value offered by @gopaltirupur above solved the problem for me.

**Comment by Kogam22** [comment] 2018-07-08 06:38
@clarkkarenl : 
> The pylintArgs value offered by @gopaltirupur above solved the problem for me.

Well, I did change them, but still 'import error'. Also I don't use venv.

**Comment by xobs** [comment] 2018-07-08 07:10
The issue is that `python.pythonPath` is different from the `PYTHONPATH` environment variable, even though they're named the same.  The vscode `python.pythonPath` parameter sets the interpreter to be used, whereas the `PYTHONPATH` environment variable sets a list of search directories to add to the `import` directive.

The solution to get programs such as `pylint` to work is to create a file in the root of your project called `.env` and add an entry for `PYTHONPATH`.  For example, the root of my Python project contains a `.env` file with the following entry:

```
PYTHONPATH=D:/Code/deps/proj1;D:/Code/deps/proj2;D:/Code/deps/proj3
```

As a result of this `.env` file, pylint gets invoked with the `PYTHONPATH` variable set to what I'd expect, and the `import` statements work just fine.

**Comment by Lucky2094** [comment] 2018-09-29 06:12
By setting below solved my problem
{
    "python.pythonPath": "C:\\<path>\\Python\\Binaries\\python.exe",
    "python.linting.pylintArgs": ["--load-plugins", "pylint_django"]
}
