### ISSUE TITLE
Go to definition not working with relative imports

### ISSUE THREAD

**Issue by rdollinger** [DonJayamanne/pythonVSCode#654] opened 2017-01-18 15:07 UTC
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.5.2
OS and version:    macOS 10.12.2

## Actual behavior

Go to definition does not work correctly with absolute imports. Sometimes also ```from your_app.models import *``` also doesn't work. When you import explicit ```from your_app.models import YourModel``` it works

## Expected  behavior

Go to definition should work also with relative imports and ```import *```

## Steps to reproduce:  

A little Django example
With this code "Go to definition" on YourModel works correctly
```python
from django.views.generic import ListView
from your_app.models import *

class YourListView(BasisListView):
    model = YourModel
```

With this one it doesn't work

```python
from django.views.generic import ListView
from .models import *

class YourListView(BasisListView):
    model = YourModel
```

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
    "python.pythonPath": "/usr/local/bin/python3.5",
    "python.linting.pylintEnabled": false,
    "python.linting.pylintArgs": ["--load-plugins", "pylint_django"],
    "python.linting.pep8Enabled": false,
    "python.linting.flake8Enabled": true,
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment] 2017-01-30 12:47
Duplicate of #352

**Closed by DonJayamanne** 2017-01-30 12:47 UTC
Labels: duplicate
