### ISSUE TITLE
Intellisense attempts completion in python comments

### ISSUE THREAD

**Issue by davehamby** [DonJayamanne/pythonVSCode#250] opened 2016-08-13 15:25 UTC
I'm new to VS Code so this may be my fault. Intellisense seems not to be aware that a comment is being typed and offers autocompletions that are pointless/not wanted.

**Comment by DonJayamanne** [comment] 2016-08-17 12:26
Part of roadmap in #183

**Comment by DonJayamanne** [comment] 2016-09-22 01:07
Closing as this is a duplicate of #74

**Closed by DonJayamanne** 2016-09-22 01:07 UTC
Labels: duplicate, enhancement
