### ISSUE TITLE
Auto Import (feature request)

### ISSUE THREAD

**Issue by ace-han** [DonJayamanne/pythonVSCode#963] opened 2017-05-17 06:37 UTC
It would be great if this plugin supports module/function `auto imports` along with `Sort Imports` from the underlying virtual environment like `pydev`

![image](https://cloud.githubusercontent.com/assets/1177332/26141428/5e085c10-3b0e-11e7-8ec7-18d284aecfd2.png)

**Comment by skyjur** [comment] 2017-06-17 12:12
Duplicate of: https://github.com/DonJayamanne/pythonVSCode/issues/764

**Closed** 2017-10-03 23:46 UTC
