### ISSUE TITLE
Format-on-save with yapf gives an invalid transformation when saving a file the first time after opening

### ISSUE THREAD

**Issue by nfvs** [DonJayamanne/pythonVSCode#1176] opened 2017-08-23 16:11 UTC
Format-on-save with yapf gives an invalid transformation, and I've had examples of code being deleted. Only happens on the first save of a just-opened file, doing undo followed by a save fixes it.

I've confirmed that running yapf manually in the command line gives the expected result, so this seems to be a pythonVSCode bug.

## Environment data
VS Code version:  1.15.1
Python Extension version:  0.7.0
Python Version:   3.6.1
OS and version:    macOS 
Yapf version: 0.17.0

## Input file
```python
logger.warning('long line long line long line long line long line long line long line: %s', 'test')
```

## Actual behavior
```python
logger.warning(
    'long line long line long line long line long line long line long line: %s',
    'test')
    'long line long line long line long line long line long line long line: %s',
    'test')
```

## Expected  behavior
```python
logger.warning(
    'long line long line long line long line long line long line long line: %s',
    'test')
```

## Steps to reproduce:  
-  Write the `Input` to a test file
-  Open the file in VS Code (with yapf and format-on-save)
- Press save (or cmd+s)

**Comment by nfvs** [comment] 2017-08-23 16:13
I suspect the problem is that initially the formatter is running twice, because after first saving the file two undo steps are available, and after undoing the first, the file is as expected.

**Comment by nfvs** [comment] 2017-08-23 16:40
Here's a gif of the bug: starts with a save (triggering the bug), followed by undoing once (showing the correct output), undoing again so we end up in the initial state, then a save that works.
 
[http://g.recordit.co/f0K5S8wRPv.gif](http://g.recordit.co/f0K5S8wRPv.gif)

**Comment by DonJayamanne** [comment] 2017-10-05 20:49
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/992

**Closed by DonJayamanne** 2017-10-05 20:49 UTC
Labels: bug, Format
