### ISSUE TITLE
No virtual environment support for debugging vs code python

### ISSUE THREAD

**Issue by cdnsteve** [DonJayamanne/pythonVSCode#91] opened 2016-04-20 18:43 UTC
Heads up for those who are trying to get debugging working in VS Code for Python.

I've tried throwing everything at it this morning, but it doesn't appear that the debugger works while using a Python 3 virtual environment. After I found the comment here confirming:
https://github.com/DonJayamanne/pythonVSCode/issues/17#issuecomment-192304402

Hopefully this saves some time.

Notes:
OSX
Tried using pyvenv and pyenv.

What happens:

Debugger boots up my Flask app, seems to trigger breakpoints right away... then the web server process runs. When I view pages in the app, with breakpoints on them, they are not triggering in the debugger. I've also read that you should manually enable all breakpoints again, which I have and this does not solve either.

**Comment by lzantal** [comment] 2016-05-21 20:59
Same here. Autocomplete and everything else works with virtualenv but when I run debug it uses the system python.

Any chance on fixing this? I really enjoy using this extension with VSCode and it is my goto editor now.

**Comment by DonJayamanne** [comment] 2016-05-22 02:50
Please could you confirm you have configured the python path setting in the launch.json file? Thanks. 

The settings file is used for intellisesnse, linting  etc and the path defined in the launch.json is used for debugging (unfortunately you do need to define this in both files)

**Comment by lzantal** [comment] 2016-05-23 17:55
That fixed it! It is not a big deal at all to add it in there. I got another error with mysql image but I will post a new ticket for it.

Thank you for your quick response.

**Comment by tugberkugurlu** [comment] 2016-05-26 15:44
@lzantal how did you get Autocomplete and other things working with virtual environments on vs code?

**Comment by lzantal** [comment] 2016-05-26 20:05
I am going to write up a blog post on it as well but I am going to post it here shortly for you. Not front of my computer atm

**Comment by lzantal** [comment] 2016-05-26 20:53
@tugberkugurlu Here you:
set python.pythonPath in .vscode/settings.json to your virtualenv/bin/python absolutely path
add the virtualenv python directories to python.autoComplete.extraPaths array
For me to make everything autocomplete on both Ubuntu and Mac I had to add it like this:
virtualenv/lib/python2.7
virtualenv/lib/python2.7/site-packages

Restart VSCode and it will auto complete everything. Even the Cmd+Click works to go to definition :)

**Comment by vanflymen** [comment] 2016-06-07 17:09
You still need to manually set the paths for linting and pep8 etc. to point to your Virtualenv...

**Comment by DonJayamanne** [comment] 2016-06-10 03:40
Closing as duplicate of #148 
For those interested #148 contains more information on making necessary config changes to get things up and running for virtual environments

**Closed by DonJayamanne** 2016-06-10 03:40 UTC

**Comment by RobsonTargz** [comment] 2016-06-10 14:53
@lzantal opening vscode from the terminal with virtualenv activated, no change in python.pythonPath is necessary. Just "python" like default settings.json, and the python of the virtualenv is used.

```
(venv) ter@minal:~$ code project_folder/
```

**Comment by DonJayamanne** [comment] 2016-06-12 10:16
Thanks for the great simple solution, will update the wiki with this simple approach typo using virtual env.

**Comment by DonJayamanne** [comment] 2016-06-16 22:59
Thanks @lzantal , that works as expected.
@cdnsteve , @lzantal @vanflymen , please could you try this approach and let me know how it goes.
If this does work, is this an approach you're happy to continue using or would you rather have something built into VS Code where by you can select your environment.

Also, for a given project, would you be selecting different environments or do you have just one environment for a single project, as in one virtual environment for each project.

**Comment by seaders** [comment] 2016-08-25 13:25
Thanks for this feature, @DonJayamanne but if possible it would be great to get this configurable per project, as often I'll be working with a number of services that will eventually, in production go to different servers, with different environments.  If you look at how LiClipse, or Eclipse with an Aptana layer on top, they provide a very full solution to the issue,

[http://i.imgur.com/jU4WzRK.png](project with venv)

[http://i.imgur.com/gtO86kR.png](selecting venv)

[http://i.imgur.com/w9m7ReJ.png](adding new venv)

**Comment by bddenhartog** [comment] 2016-08-29 17:58
@DonJayamanne Was asking myself the same question this morning, googled this, and found the result. Figured I would reply to your last comment; a virtual environment, in reference to python projects, is used on a per-project basis. 

Also, in my opinion, it would be ideal to be able to integrate the usage of a virtualenv locally. One method for accomplishing this would be ensuring that the `python.pythonPath` workspace setting works when using a relative path, e.g. `./myenv/python`, where `.` means "the current directory". I'm not familiar with VSCode's codebase so I'm not sure how feasible / possible this is, but that would, in my opinion, be the most modular solution (meaning that the workspace settings file could be shared _with_ the project, like intended, without having to have users edit the path manually to match where the codebase lives on their system). Currently, it looks like the full path is required for this setting, which makes it impossible to share the workspace setting file with other users.

**Comment by DonJayamanne** [comment] 2016-08-30 22:42
@bddenhartog , using relative paths will work for intellisense, etc, however when it comes to debugging, this will not work. 
Hence the only solution is to provide the absolute path.
One quick trick (**something to be documented**) is the use of the $workspaceRoot.

So all you'll need to do is:
```python.pythonPath = '$workspaceRoot/myenv/python'```

**Comment by DonJayamanne** [comment] 2016-08-30 22:51
@bddenhartog , the wiki has been updated accordingly  
- [Relative Paths](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#relative-paths-to-python-interpreter)
- [Environment Variables](https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version#environment-variables-when-configuring-python-interpreter)
