### ISSUE TITLE
Auto Docstring generation

### ISSUE THREAD

**Issue by srinath29** [DonJayamanne/pythonVSCode#842] opened 2017-03-23 13:39 UTC
## Environment data
VS Code version:  1.10.2
Python Extension version: 0.6.0  
Python Version:   3.6
OS and version:    windows 7 service pack1

Hi
This is more like a feature request. Before using VScode with your extension. I used to use pycharm from jet-brains. It is a powerful IDE. It had one interesting feature I used to use most is the auto auto docstring generation.
How it used to work was as soon as I type function declaration and pressed enter and used """ <Enter Key> like magic all the docstring used to get generated. If the function takes some input parameters then those things will come in the comments by default. If you use it you can understand how awesome it is.

There is a community edition available for it. Please check it out. 

p.s. Recently visual studio code devs put a feature something like that for javascript, you need to do /** <Enter key>, it will automatically come. 

Thanks & Regards
Srinath

**Comment by DonJayamanne** [comment] 2017-04-06 11:40
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/165

**Closed by DonJayamanne** 2017-04-06 11:40 UTC
