### ISSUE TITLE
Find all references not working, but go to work fine.

### ISSUE THREAD

**Issue by seanmars** [DonJayamanne/pythonVSCode#840] opened 2017-03-22 07:21 UTC
## Environment data
VS Code version:  1.10.2
Python Extension version:  0.6.0
Python Version:   3.5.2
OS and version:    windows 10

## Actual behavior
Just use find all references(shift+F12)

## Expected  behavior
Show all the references.

## Steps to reproduce:  
-  On the method right click and select Find all references.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
// USER SETTINGS
{
    "window.title": "${appName}${separator} | ${rootName} | ${rootPath}${separator}${activeEditorMedium}",

    "editor.fontFamily": "Fira Code,Envy Code R VS, Consolas, 'Courier New', monospace",
    "editor.fontSize": 18,
    "editor.fontLigatures": true,

    "editor.minimap.enabled": true,
    "editor.minimap.renderCharacters": false,

    "editor.renderWhitespace": "boundary",
    "editor.renderControlCharacters": true,
    "editor.renderIndentGuides": true,

    "editor.wordWrapColumn": 120,
    "editor.wordWrap": "wordWrapColumn",
    "editor.wrappingIndent": "same",
    "editor.rulers": [
        80
    ],

    "files.associations": {},
    "files.autoSave": "afterDelay",
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/__pycache__": true
    },

    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Material Theme",

    "python.linting.pep8Enabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,

    "workbench.welcome.enabled": false
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment] 2017-04-04 12:23
Please could you provide a sample code to replicate this issue.

**Comment by seanmars** [comment] 2017-04-05 15:01
There is a sample code i created.
https://drive.google.com/open?id=0B_Q2LyrK-IOMVlA1STZJTEE3aU0

And I just take a snapshot too.

![issue](http://i.imgur.com/yLdwV0y.png)

**Comment by Crazy-Owl** [comment] 2017-07-14 13:22
I experience this behavior as well

**Comment by suheti** [comment] 2017-09-29 07:43
Is there anyway to make it work for the entire project, not just opened files?

**Comment by embano1** [comment] 2017-10-12 12:09
I´m also having a hard time understanding how "Find all references" is expected to behave. Sometimes it just "references" back to the function call I´m investigating. Sometimes it shows more references, sometimes just go_test files. As a workaround, I use Sourcegraph since this works reliably and I expected vscode to behave the same way.

**Comment by DonJayamanne** [comment] 2017-10-12 16:14
@embano1 , please could you provide additional information thanks.

**Comment by DonJayamanne** [comment] 2017-10-12 16:31
@seanmars apologies for never getting back to you on this. 
I believe the problem is with the Python Package ([Jedi](https://github.com/davidhalter/jedi)) I'm using to provide this functionality.

**Comment by embano1** [comment] 2017-10-13 12:36
@DonJayamanne Sure, sorry for brevity. I found out that during my tests, I was running an older gocode version (although I closed & updated, somehow it remained active...my fault). Closing, updating and restarting gocode/ godef/ vs-code to the latest version as well as using a clean go path for testing now works as expected for "Find all references". Sorry for any inconvenience.

**Closed** 2017-10-13 15:28 UTC
Labels: Intellisense, Need more info
