### ISSUE TITLE
Debug Error about numpy

### ISSUE THREAD

**Issue by liandaoacc** [DonJayamanne/pythonVSCode#110] opened 2016-05-06 01:29 UTC
I want to use the plugin to debug some program using numpy. But I got an error `ImportError, cannot import name float96` when I ran `import numpy as np` in debug.
- OS is ubuntu 14.04 LTS
- Visual studio code is 0.10.11, Commit f291f4ad600767626b24a4b15816b04bee9a3049
- python plugin is 0.3.3
- numpy is 1.8.2, installed by `apt-get install python-numpy'
- python is 2.7.6
I can debug the same program using spyder, so I report this problem.

**Comment by DonJayamanne** [comment] 2016-05-10 23:32
Have you configured the path to python in launch.json.
https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

**Comment by McNull** [comment] 2016-05-16 12:14
This is related to exception handling issue -> https://github.com/DonJayamanne/pythonVSCode/issues/107

**Comment by DonJayamanne** [comment] 2016-05-16 13:22
Thanks, will close this as it is a duplicate of #107

**Closed by DonJayamanne** 2016-05-16 13:22 UTC
