### ISSUE TITLE
"go to definition" is useless for custom packages

### ISSUE THREAD

**Issue by wayne508** [DonJayamanne/pythonVSCode#64] opened 2016-04-05 09:08 UTC
Hi, 
The "go to definition" function seems useless when a custom package imported another custom package.
VScode: 0.10.11
python ext:0.3.1

Thanks

**Comment by DonJayamanne** [comment] 2016-04-05 09:11
Do you mean it doesn't work, If so please could you provide some more information?
Have you tried configuring the path as per the wiki?
https://github.com/DonJayamanne/pythonVSCode/wiki/Autocomplete-Intellisense

**Comment by wayne508** [comment] 2016-04-05 09:34
Thanks for your reply.
For example, my workspace looks like:
```
workspace
├─core
│  ├─__init__.py
│  ├─a.py
│  └─b.py
│   ...
│  └─xxx.py
├─schemes
│  ├─__init__.py
│  └─s.py
├─main.py
```
s.py imported a.py, however "go to definition" is useless in s.py.

===============================================================

I tried to add my workspace path to "setting.json". It works!
```
"python.autoComplete.extraPaths": ["E:/my_project_path" ]
```

When "go to definition" is applied to "s.py", it seems only the path "schemes" is added to sys.path.

Thanks!

**Comment by martinpengellyphillips** [comment] 2016-04-30 12:55
I'm seeing this also when unit tests are in a separate top level folder:

```
├───source
│   └───clique
└───test
    └───unit
```

References in the tests to the package `clique` do not resolve until adding the `source` folder to the `python.autoComplete.extraPaths` setting.

**Comment by DonJayamanne** [comment] 2016-07-18 04:55
@martinpengellyphillips , @wayne508 . Apologies for the delay in looking at this issue. Are you still experiencing this issue, I am unable to replicate this at my end.

**Comment by DonJayamanne** [comment] 2016-07-18 05:43
@wayne508 , @martinpengellyphillips , the problem is with the directory structure. I believe you're trying to use relative imports. In this scenario each folder will have to be treated as a separate package and the root directory (will have to be treated as a package in its own right).

Placing a _**__init__.py**_ at the root level will fix the issue:
```
workspace
├─core
│  ├─__init__.py
│  ├─a.py
│  └─b.py
│   ...
│  └─xxx.py
├─schemes
│  ├─__init__.py
│  └─s.py
├─main.py
├─__init__.py
```

**Comment by martinpengellyphillips** [comment] 2016-07-20 08:53
Hey - there are some relative imports within the package and the test folders. Is that what you mean?

For reference, here is the full repo that I see the issue in: https://gitlab.com/4degrees/clique

**Comment by DonJayamanne** [comment] 2016-07-20 08:56
Great, will look into this soon.

**Comment by martinpengellyphillips** [comment] 2016-07-20 09:02
Thanks!

Additional information: I am using a Virtualenv and have set the "python.pythonPath" variable to the Virtualenv Python, but have not `pip installed -e .`

If I do `pip install -e`  the package then the references in `test` do resolve.

**Comment by DonJayamanne** [comment] 2016-09-22 13:56
Closing as there is a solution,

**Closed by DonJayamanne** 2016-09-22 13:56 UTC
Labels: enhancement
