### ISSUE TITLE
Jupyter Command: strk, Id: 1, Python Trace: Traceback (most recent call last):

### ISSUE THREAD

**Issue by jackwluo** [DonJayamanne/pythonVSCode#593] opened 2016-12-18 04:31 UTC
## Environment data
VS Code version:  1.8.0
Python Extension version:  Jupyter 1.0.0
Python Version:   2.7
OS and version:  macOS 10.12 Sierra

----------Generating Tags----------
ctags --options=/Users/Admin/.vscode/extensions/donjayamanne.python-0.5.5/resources/ctagOptions --languages=Python -o /Users/Admin/.vscode/extensions/donjayamanne.python-0.5.5/out/client/common/tags .
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
Error Message: Command: strk, Id: 0, Python Trace: Traceback (most recent call last):
  File "/Users/Admin/.vscode/extensions/donjayamanne.python-0.5.5/pythonFiles/PythonTools/ipythonServer.py", line 283, in start_processing
    cmd(self, id)
  File "/Users/Admin/.vscode/extensions/donjayamanne.python-0.5.5/pythonFiles/PythonTools/ipythonServer.py", line 370, in _cmd_strk
    kernelUUID = multiKernelManager.start_kernel(kernel_name=kernelName)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/connect.py", line 407, in write_connection_file
    kernel_name=self.kernel_name
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/connect.py", line 135, in write_connection_file
    with open(fname, 'w') as f:
IOError: [Errno 13] Permission denied: u'kernel-8af27731-2072-45cf-9e6b-9f7090b621bd.json'

**Comment by thejackluo** [comment] 2016-12-18 12:45
Tried reinstalling jupyter on both pip2 pip3, tried setting python env path but to no avail

**Comment by Twizzledrizzle** [comment] 2016-12-18 16:00
I got it to work with anaconda python 3.5, had similar problems with 2.7

**Comment by thejackluo** [comment] 2016-12-18 16:02
Did pip install work for you or did you need anaconda?

**Comment by Twizzledrizzle** [comment] 2016-12-18 16:48
I uninstalled and reinstalled anaconda with the graphical installer (Windows)

**Comment by thejackluo** [comment] 2016-12-18 16:55
About to switch to atom + hydrogen lol, this is such a mess

**Comment by thejackluo** [comment] 2016-12-29 22:32
Any solution for pip install?

**Comment by thejackluo** [comment] 2017-01-08 17:27
Reinstalled macOS (10.12) with Anaconda python 3.5
Running Jupyter inline still throws the same error, maybe the issue is macOS specific?

@DonJayamanne

**Comment by starfishdemon** [comment] 2017-01-21 20:02
I can confirm that I have the same issue on Windows with VSCode 1.8.1, Python 2.7, Python Extension version 0.5.6. For me the issue has to do with having permissions to write to the main VSCode directory. It looks like jupyter is trying to write to kernel-8af27731-2072-45cf-9e6b-9f7090b621bd.json in the C:\Program Files (x86)\Microsoft VS Code\ directory. Because the user normally doesn't have rights to that directory, the attempt fails with the above error. Taking ownership of that folder solves the issue but feels insecure/a hack. Having the plugin start the kernel in the user's temp folder instead of the main program install directory would probably fix the problem.

I imagine something similar is happening on Mac OS. I would try to take ownership of the IDE app to see if it helps.

**Comment by ivan-krukov** [comment] 2017-01-24 05:00
Is this a duplicate of #483?

**Comment by thejackluo** [comment] 2017-01-24 05:47
Not quite, sorry

**Comment by DonJayamanne** [comment] 2017-03-09 14:13
This issue was moved to DonJayamanne/vscodeJupyter#12

**Closed by DonJayamanne** 2017-03-09 14:13 UTC
Labels: Jupyter
