### ISSUE TITLE
Pyramid debug on Windows fails due to "file not found: pserve"

### ISSUE THREAD

**Issue by jpfarias** [DonJayamanne/pythonVSCode#1393] opened 2018-01-03 16:46 UTC
## Environment data
VS Code version:  1.19.0
Python Extension version:  0.9.1
Python Version:   3.6
OS and version:    Windows 10

## Actual behavior

Trying to run / debug a pyramid application fails due to "File not found: pserve"

## Expected  behavior

Run / debug using pserve.exe

## Steps to reproduce:  
-  Create a pyramid application on windows
-  Setup a launch configuration for the pyramid application
- Try to run or debug the application

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
``` 
File does not exist. "c:\work\genv\scripts\pserve"
e.doShow @ messageService.ts:126
```

**Comment by DonJayamanne** [comment] 2018-01-03 19:23
Duplicate of https://github.com/Microsoft/vscode-python/issues/519

**Comment by DonJayamanne** [comment] 2018-01-03 19:24
@jpfarias Please report issues on https://github.com/Microsoft/vscode-python/issues
The extension is officially maintained on the Microsoft Fork, we'll look into issues from there.

**Closed by DonJayamanne** 2018-01-03 19:23 UTC

**Comment by jpfarias** [comment] 2018-01-03 19:34
Yeah, sorry, when I forked the code from Microsoft github actually created a fork from this repository here. I thought I should report here then. Will keep it in mind from now on.
