### ISSUE TITLE
Feature Request: Automatic docBlocks 

### ISSUE THREAD

**Issue by asierralozano** [DonJayamanne/pythonVSCode#900] opened 2017-04-20 11:09 UTC
Hello!!

I'm wondering if you can implement an auto docblock feature.

Here i let you a SublimePlugin that do exactly this:

https://github.com/adambullmer/sublime_docblockr_python

Thank you very much!!

PD: I don't know it this is the best place to do a request like this. If you need to move it, just do it :)

**Comment by DonJayamanne** [comment] 2017-09-14 16:53
Duplicate of #165

**Closed by DonJayamanne** 2017-09-14 16:53 UTC
Labels: Docstring, enhancement
