### ISSUE TITLE
Formatting with autopep8 failed.

### ISSUE THREAD

**Issue by XianwuLin** [DonJayamanne/pythonVSCode#188] opened 2016-06-28 14:03 UTC
Error: Illegal escape in patch_fromText: 

python output
![](http://i1.piimg.com/567571/a0822eb9337d497b.png)

**pythonvscode version: 0.3.16**
**vs code version: 1.2.1**
**os: win7 x64**

**Comment by DonJayamanne** [comment] 2016-06-28 21:33
Please could you upload the text that you are trying to format. Thanks.

**Comment by XianwuLin** [comment] 2016-06-29 01:18
```python
# -*- coding: utf-8 -*-
# Author: Linxianwu

import sys
import re

def parse(command):
    command = command.strip()
    
    sff_name_str = r"(?P<obj>section|folder|file) (?P<obj_name>\S+)"
    ff_name_str = r"(?P<obj>folder|file) (?P<name>\S+)"
    s_name_str = r"(?P<obj>section) (?P<name>\S+)"
    location_str = r"(?P<location>AFTER|BEFORE) (?P<location_name>\S+)"
    in_str = r"IN (?P<in_name>\S+)"

    re_add = []
    re_add.append(re.compile(r'ADD %s %s' % (sff_name_str, location_str) , re.I))
    re_add.append(re.compile(r'ADD %s %s %s' % (ff_name_str, location_str, in_str), re.I))
    re_add.append(re.compile(r'ADD %s' % (s_name_str), re.I))

    re_del = []
    re_del.append(re.compile(r'DELETE %s' % (s_name_str), re.I))
    re_del.append(re.compile(r'DELETE %s %s' % (ff_name_str, in_str), re.I))

    re_move = []
    re_move.append(re.compile(r'MOVE %s %s' % (s_name_str, location_str) , re.I))
    re_move.append(re.compile(r'MOVE %s %s %s' % (ff_name_str, location_str, in_str), re.I))

    re_alter = []
    re_alter.append(re.compile(r"ALTER %s" % (s_name_str), re.I))
    re_alter.append(re.compile(r"ALTER %s %s" % (ff_name_str, in_str), re.I))

    for _re_command in re_add + re_del + re_move + re_alter:
        m = _re_command.match(command) 
        if m:
            operator = command.lower().split(" ")[0]
            gdict = m.groupdict()
            gdict['obj'] = gdict['obj'].lower()
            gdict['location'] = gdict['location'].lower()
            return (operator, gdict)

    # if any re expression can't match command, there will raise except
    raise SyntaxError("`%s` syntax error" % command)

def main():
    print parse("ADD section s1 AFTER s0")
    print parse("MOVE file fi5 before f2 in s0.fo1.fi2")
    print parse("DELETE folder f1 in s0")
    print parse("ALTER folder fo1 in s1")
    return 0

if __name__ == '__main__':
    sys.exit(int(main() or 0))

```

**Comment by DonJayamanne** [comment] 2016-06-29 02:14
@XianwuLin , thanks for that. I've identified the issue and have a fix ready.
The fix will be in the next release.
For some reason the popular google library being used to generate differences between texts is encoding  the text (this doesn't seem to be the standard ouput generated by python libraries).

I have a fix, thats the important part. I'll investigate this further to find the root cause, as opposed to patching it.

**Comment by XianwuLin** [comment] 2016-06-29 02:22
thanks

**Comment by DonJayamanne** [comment] 2016-06-29 21:43
Fixed in latest build.

**Comment by DonJayamanne** [comment] 2016-06-29 21:43
Please try and close if issue is resolved

**Comment by XianwuLin** [comment] 2016-06-30 00:49
thx

**Closed** 2016-06-30 00:49 UTC
Labels: bug
