### ISSUE TITLE
Improved hover info formatting

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#344] opened 2016-09-30 02:30 UTC
Especially in packages with large interfaces, like Pandas, I frequently get really long hover info that ends up covering most, if not all of the screen. The documentation itself is not formatted well, perhaps there may be a way to display it better?

![capture](https://cloud.githubusercontent.com/assets/21064086/18978755/aa894e26-8693-11e6-9db1-572d59449364.PNG)

![capture2](https://cloud.githubusercontent.com/assets/21064086/18978860/4ea04cee-8694-11e6-9813-4088e7aa3150.PNG)

**Comment by DonJayamanne** [comment] 2016-10-03 00:12
Duplicate of #113

**Closed by DonJayamanne** 2016-10-03 00:12 UTC
Labels: duplicate
