### ISSUE TITLE
pythonVSCode's doesn't easily handle python3 code (defaults to python 2 linting)

### ISSUE THREAD

**Issue by manad777** [DonJayamanne/pythonVSCode#851] opened 2017-03-29 20:36 UTC
## Environment data
VS Code version:  1.10.1
Python Extension version:  0.6.0
Python Version:   3.5.2
OS and version:  Ubuntu 16.04

## Actual behavior
linter incorrectly flags python 3 code 

## Expected  behavior
it shouldn't

## Steps to reproduce:  
-  Write the statement: print("hello"). The linter will report superfluous parenthesis.

## Settings  
Your settings.json:   
```json
{
    "python.formatting.provider": "autopep8",
    "python.pythonPath": "python3",
}
```   

Installing pylint3 on the system, then setting python.linter.pylintPath to pylint3, fixes the issue. But this isn't mentioned anywhere in the setup doc/wiki.

My suggestion is that when pythonVSCode is given a python3 pythonPath, it auto-applies all the settings that are appropriate for python3 development, so the user doesn't have to hunt down these things by him/herself. After all, it doesn't make sense to use a python2 linter for a python3 interpreter.

**Comment by DonJayamanne** [comment] 2017-04-06 11:31
Duplicate of #843

**Closed by DonJayamanne** 2017-04-06 11:31 UTC
Labels: enhancement, Linter
