### ISSUE TITLE
Support automatic re-indentation better

### ISSUE THREAD

**Issue by gandhis1** [DonJayamanne/pythonVSCode#679] opened 2017-01-27 16:13 UTC
Recently a "Reindent All Lines" command was added to VS Code here: https://github.com/Microsoft/vscode/pull/18958

Using it in a Python file, on the latest Insiders build, appears to do absolutely nothing. Is this expected? Is it possible to support these language-specific indentation rules better so that features like the one mentioned above can work better?

**Comment by DonJayamanne** [comment] 2017-01-27 21:02
Not sure how I would support this. Low priority for now.

**Comment by DonJayamanne** [comment] 2017-02-02 07:52
Unfortunately I don't see a simple way of implementing this with the use of the regular expressions. The problem is in Python there's no way of identifying using regular expressions whether a class, def (body) has ended or not. Unless someone knows how to resolve this, I'm closing this.

**Closed by DonJayamanne** 2017-02-02 07:52 UTC

**Comment by gandhis1** [comment] 2017-02-03 03:20
What was wrong with the Atom regex that @rebornix linked to? 

https://github.com/atom/language-python/blob/719e4404d2cd25a888a8111c62abd31a22a15ef3/settings/language-python.cson#L7

**Comment by DonJayamanne** [comment] 2017-02-03 03:27
It didn't work, that works for just indentation as you type. Which is what I already have in the extension.
