### ISSUE TITLE
Python/Django project not debugging in virtualenv

### ISSUE THREAD

**Issue by intoCL** [DonJayamanne/pythonVSCode#954] opened 2017-05-11 20:02 UTC
I have seen similar issues submitted [here](https://github.com/DonJayamanne/pythonVSCode/issues/148) and [here](https://github.com/DonJayamanne/pythonVSCode/issues/913) and have cobbled together settings.json and launch.json configurations as appropriate but still not getting any joy. We're Django and Python noobs.

## Environment data
VS Code version: 1.11.2
Python Extension version:  0.6.4
Python Version: 3.4 [I assume]
OS and version: Kubuntu 14.04 LTS

## Actual behavior
When running debug on manage.py (I haven't configured {file} in the Python launch configuration), the Debug Console runs but no breakpoints are hit (well they might be but not visualised).

## Expected  behavior
Well...it needs to break at breakpoints...

## Steps to reproduce:  
```
sudo apt-get install python3
sudo apt-get  install python3-pip
sudo pip install virtualenv

mkdir myenvironments
cd myenvironments

virtualenv -p /usr/bin/python3 myenv1
```

To confirm virtualenv version install, I'm providing the bin listing here.

![1 - bin folder](https://cloud.githubusercontent.com/assets/25256514/25968646/afb27262-3668-11e7-9ec4-1b8da50b4ceb.png)

```
cd myenv1
. bin/activate // at this point everything happens under virtual environment

pip install djangocms-installer
djangocms -w -p mywebproject mainwebsite
```

Obviously, I don't think that Django is the culprit here at all. I'm just putting the install steps in for completeness's sake, and just in case I'm making a really massive stupid assumption.

Here's the Django config:

```
Database configuration: Enter
Django CMS Configuartion: 3.3
Django version: 1.9
Django I18N/L10N: yes
Reversion support: yes
Languages to enable: en
Optional default timezone: Enter
Timezone support: yes
CMS permission management: no
Bootstrap theme: no
Custom template set: no
Load example after installation: yes

Add admin credentials as appropriate
Add email address as appropriate
```
Now to check that everything runs from terminal.

```
cd mywebproject
python manage.py runserver
```
The server should launch and bind to the appropriate port.
Kill the server [Ctrl+C]

`code . //to open mywebproject [still in activated virtual environment]`

Modify settings.json and launch.json according to configurations below.
Save and close VS Code.

`code .`

Open manage.py and set breakpoints
Click Debug button. Select Python configuration
Start debug.

Debug Console shows:

```
Performing system checks...
System check identified no issues (0 silenced).
May 11, 2017 - 21:58:25
Django version 1.9.13, using settings 'mainwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
## Settings  

Your launch.json (if dealing with debugger issues):  
```json
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "[FULLYQUALIFIEDPATHPREFIX]/myenvironments/myenv1/bin/python3",
            "program": "[FULLYQUALIFIEDPATHPREFIX]/myenvironments/myenv1/mywebproject/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
```   
Your settings.json:   
```json
	"python.pythonPath": "[FULLYQUALIFIEDPATHPREFIX]/myenvironments/myenv1/bin/python3"
```   
## Logs
Output from ```Python``` output panel  
```
Performing system checks...
System check identified no issues (0 silenced).
May 11, 2017 - 21:58:25
Django version 1.9.13, using settings 'mainwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
No output
```

**Comment by intoCL** [comment] 2017-05-11 20:21
OK, I should point out that it _is_ launching into the debug environment. I can see context variables and the call stack being populated. It's just not visualising the current line of execution so you have to step through blindly. This _isn't_ the case if I create a Python script with some test prints outside of the virtual environment directory and open it in code. If I do that then the current line visualisation works in debug.

**Comment by DonJayamanne** [comment] 2017-05-12 22:58
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/937#issuecomment-301193493

**Closed by DonJayamanne** 2017-05-12 22:58 UTC
