### ISSUE TITLE
Run python file in Terminal: can't work if default terminal is powershell

### ISSUE THREAD

**Issue by MisLink** [DonJayamanne/pythonVSCode#668] opened 2017-01-20 19:24 UTC
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   3.5.2 x64
OS and version:    windows 10 x64

## Actual behavior
Get an error "The expression or statement contains an unexpected token."
Because powershell regard "python" (from setting "python.pythonPath") as string, not command.
## Steps to reproduce:  
-  use powershell as default terminal.
-  create a test python file.
-  run command "run python file in terminal".

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.formatting.provider": "autopep8",
    "python.formatting.formatOnSave": true,
    "python.linting.flake8Args": [
        "--ignore",
        "E501",
        "--exclude",
        "tmp-*.py"
    ],
    "python.formatting.autopep8Args": [
        "--max-line-length",
        "120"
    ],
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)

**It's Chinese output because I'm not native English speaker.**
**The longest sentence means "The expression or statement contains an unexpected token".**
```
所在位置 行:1 字符: 11
+ "python" d:/Untitled-1.py
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“d:/Untitled-1.py”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by DonJayamanne** [comment] 2017-01-23 20:21
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/651

**Closed by DonJayamanne** 2017-01-23 20:21 UTC
Labels: duplicate, Misc
