### ISSUE TITLE
Unverified Breakpoints with "Python" or "Integrated Teminal/Console" 

### ISSUE THREAD

**Issue by mike-pt** [DonJayamanne/pythonVSCode#791] opened 2017-03-05 16:02 UTC
## Environment data
VS Code version:  1.10.1
Python Extension version:  0.5.9
Python Version:   2.7
OS and version:    Windows 10

## Actual behavior
Trying to set break points on inner modules set then as `Unverified Breakpoint` and debugger skips those, setting than on the `program` file seems to work.

## Expected  behavior
It should be possible to create breakpoints anywhere in the code, even if its not the "program" file

Not sure if its related to my custom launch config, but I'm simply specifying args and the program to run

My launch.json (if dealing with debugger issues):  
```json
{
            "name": "runTest.py Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/runTest.py",
            "args" :[  
                "-l", "cpms",
                "-a", "true",
                "-t", "pms",
                "--run-type", "stagger",
                "--stagger-time", "10",
                "--se", "addLibraries",
                "-e", "stage"
            ],
            "cwd": null,
            "console": "integratedTerminal",
            "env": null,
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
```   

The same thing happens if I use args/program in a similar way on "python" (without Terminal/Console).

Keeping program as "${file}"  also ends in the same behavior.

**Comment by mike-pt** [comment] 2017-03-06 15:53
I wonder if this is similar too --> https://github.com/Microsoft/vscode-go/issues/689 ?

The problem seems like the same, and maybe this can hint on a solution...

**Comment by mike-pt** [comment] 2017-05-10 14:32
This still happens in the most recent stable version on vscode and pythonVSCode, however its a bit different.

I'm able to "stop at the breakpoint" but its still marked unverified? :|

**Comment by gandhis1** [comment] 2017-05-10 14:50
Yes, I can stop at the breakpoint, but it is never verified, even when it stops at the breakpoint. I reported this in #940 but I'm closing it as a duplicate of this one.

**Comment by mike-pt** [comment] 2017-07-06 23:15
any update on this?

**Comment by DonJayamanne** [comment] 2017-11-13 22:41
This issue was moved to Microsoft/vscode-python#87

**Closed by DonJayamanne** 2017-11-13 22:41 UTC
Labels: Debugger, m
