### ISSUE TITLE
How to get all parameter info when filling in a function param list

### ISSUE THREAD

**Issue by horserma** [DonJayamanne/pythonVSCode#598] opened 2016-12-22 00:48 UTC
- VSCode Version:1.8.1 
- OS Version:MAC OS

Hi guys, I am using vscode for writing python code. I found when I tried to fill in a function with parameters, the hint will be shown one by one instead of all. For example, if the function has 3 parameters, the hint will show the first one first and after I fill in it and write a comma, the second will be triggered. I just want to show them all to get clear what parameters I am going to fill in. Any suggestions?

**Comment by gandhis1** [comment] 2016-12-22 00:49
I agree with this. Many IDEs show the whole function signature, with the current argument in bold.

**Comment by spitis** [comment] 2017-02-26 21:46
+1. If possible to replicate Jupyter's autocomplete on this front (shows full signature + docstring), it would be perfect.

**Comment by gandhis1** [comment] 2017-03-07 19:32
As an example, the hover box is very informative and useful:

![image](https://cloud.githubusercontent.com/assets/21064086/23674109/c31c8f4e-0342-11e7-8889-e14cb4d7d8da.png)

But the intellisense when typing shows only 1 parameter, with no syntax highlighting or docstring - comparatively less helpful.

![image](https://cloud.githubusercontent.com/assets/21064086/23674146/e47b13cc-0342-11e7-8369-6194678b01d9.png)

**Comment by gpassero** [comment] 2017-04-03 14:22
Iy would be really nice to show the parameter type, as it happens in Visual Studio:

![image](https://cloud.githubusercontent.com/assets/4478523/24613813/ce6707bc-185f-11e7-9bc3-517e6a096970.png)

VS Code:

![image](https://cloud.githubusercontent.com/assets/4478523/24613824/dcfefa14-185f-11e7-86d8-b6102220c796.png)

**Comment by haarburger** [comment] 2017-10-06 12:55
This may be a duplicate of #848 ...

**Comment by ahpearce** [comment] 2017-10-12 16:12
+1

**Comment by corenel** [comment] 2017-10-19 09:33
Looking forward to this enhancement.

**Comment by DonJayamanne** [comment] 2017-11-13 22:40
Closing in favor of https://github.com/Microsoft/vscode-python/issues/70

**Closed by DonJayamanne** 2017-11-13 22:40 UTC
Labels: enhancement, Intellisense, m
