### ISSUE TITLE
Chinese path can not use python feature

### ISSUE THREAD

**Issue by tongguang** [DonJayamanne/pythonVSCode#172] opened 2016-06-19 09:37 UTC
if i open an path like x:\\测试\\test, then i can not use python feature, like autocomplete. 
I think it is a result of Chinese path

**Comment by DonJayamanne** [comment] 2016-06-19 11:46
Unfortunately, the debugger and features such as auto complete don't work too well with unicode characters. This is being investigated at the moment.
As this is a duplicate of #40 , i'll be closing this.

**Closed by DonJayamanne** 2016-06-19 11:46 UTC
