### ISSUE TITLE
Idea: allow configuring environment variables for unit tests

### ISSUE THREAD

**Issue by tdbear** [DonJayamanne/pythonVSCode#576] opened 2016-12-10 20:44 UTC
Can not specify environment variables for unit test execution by the unit test integration. 

Environment variables can be used to supply test database connection URL and other.

**Comment by tdbear** [comment] 2016-12-11 14:33
Is there a way to work around this issue? I can't run my tests using unit test integration because they reply on a couple of environment variables. Thank you!

**Comment by DonJayamanne** [comment] 2017-03-05 13:34
With the new version of the extension you can place your environment variables in a file named '.env' in the project directory (workspace directory) and it will get picked up.

Here's the default setting in settings.json (for picking up .env files)
```json
"python.envFile": "${workspaceRoot}/.env"
```

**Comment by Kurara** [comment] 2017-03-06 08:30
@DonJayamanne I was searching how to launch program in virtualenv is that envFile something relate to it? I don't know how to configure virtualenv with your plugin, if it's posible.

**Comment by DonJayamanne** [comment] 2017-03-06 08:59
The information on configuring VS Code to use Virtual Environments can be found here: https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

**Comment by tdbear** [comment] 2017-03-13 22:45
`python.envFile` does not seem to have any effect. Is there documentation on this variable?

**Comment by chirag04** [comment] 2017-03-21 23:11
@DonJayamanne I can confirm `python.envFile` has no effect when debugging tests

**Comment by itamarhaber** [comment] 2017-06-14 13:14
Yep - no evidence nor code lines suggesting that it is used by the test Server.

**Comment by DonJayamanne** [comment] 2017-10-19 17:20
Closed, cannot find the commit/issue under which it was resolved.

**Comment by chirag04** [comment] 2017-10-19 18:27
@DonJayamanne with 0.7 setting `"python.envFile": "/Users/chirag/Desktop/project/variables-test.env"` didn't work for me.

**Comment by DonJayamanne** [comment] 2017-10-19 18:48
Just tested in the latest dev branch, it works there. Please wait for the next release.

**Comment by DonJayamanne** [comment] 2017-10-19 18:52
>@DonJayamanne I can confirm python.envFile has no effect when debugging tests 

Ok, looks like you're referring to debugging unit tests
Will reopen and confirm this has been fixed if not, hang in there.

**Comment by chirag04** [comment] 2017-10-19 19:06
@DonJayamanne sorry for not making it clear. yeah, i was trying to "debug" unit tests.

**Comment by DonJayamanne** [comment] 2017-11-10 23:04
Fixed in latest version (Microsoft version of the Python extension)

**Closed by DonJayamanne** 2017-11-10 23:04 UTC
Labels: bug, m, UnitTest
