### ISSUE TITLE
feature request: Show function arguments / docstring while typing

### ISSUE THREAD

**Issue by wAuner** [DonJayamanne/pythonVSCode#848] opened 2017-03-28 13:28 UTC
Current behavior: The docstring of a function shows up when I hover over of the function or module, but disappears as soon as I type within the brackets.
![bildschirmfoto vom 2017-03-28 15-23-45](https://cloud.githubusercontent.com/assets/18383180/24407193/98d550f2-13ca-11e7-9b82-c0563550366a.png)

It would be great if there was a setting so that the window doesn't disappear while I'm filling in the function arguments and if I could call the docstring with a shortcut. Like in jupyter notebook where you can open a popup with shift+tab. This is extremely helpful for working with new libraries.

**Comment by haarburger** [comment] 2017-10-06 12:54
This is exactly what I was also looking for. Unfortunately I couldn't find any command in the keymap list that triggers such a behaviour..

**Comment by DonJayamanne** [comment] 2017-10-06 14:08
Duplicate of #598

**Closed by DonJayamanne** 2017-10-06 14:08 UTC
Labels: enhancement, Intellisense
