### ISSUE TITLE
pylint linter does not lint automatically on text changes

### ISSUE THREAD

**Issue by RickyZhangCA** [DonJayamanne/pythonVSCode#1359] opened 2017-10-31 13:43 UTC
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.8.2
Python Version:   3.6.3
OS and version:    Windows 10, version 1709, build 16299.19

## Actual behavior
![image](https://user-images.githubusercontent.com/16908811/32226507-15b8afca-be1f-11e7-9a8c-af90ac30be4d.png)
0. Both lint on text change and on save enabled.

![image](https://user-images.githubusercontent.com/16908811/32226382-da6aaa5e-be1e-11e7-81bb-c9033163478e.png)
![image](https://user-images.githubusercontent.com/16908811/32226599-55706b62-be1f-11e7-8518-6e768227466d.png)
1. linter did not work when "true" was typed in, and after something else was typed in.

![image](https://user-images.githubusercontent.com/16908811/32226356-cbb4c616-be1e-11e7-967d-1426bc86bd6e.png)
2. linter worked only when file was saved.

## Expected  behavior

Currently it only lints when file saved but not when text is changed although this feature is enabled.

## Steps to reproduce:  
-  type in something wrong that should trigger the linter (lint when text changes does not work)
-  linting does not exist until file saved (lint when file saved works)

**Comment by DonJayamanne** [comment] 2017-10-31 15:04
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/1205

**Closed by DonJayamanne** 2017-10-31 15:04 UTC
