### ISSUE TITLE
 module from Boost.Python wrapper can't parse correctly

### ISSUE THREAD

**Issue by platinhom** [DonJayamanne/pythonVSCode#1342] opened 2017-10-26 13:05 UTC
## Environment data
VS Code version:  1.17.2
Python Extension version:  0.7.0
Python Version:   2.7.13
OS and version:    Win10 64bit

## Actual behavior

I'm using [rdkit](https://github.com/rdkit/rdkit) in Python. Some of the modules are built from C++ and wrapped by Boost.Python.  In these modules, pythonVSCode couldn't parse it correctly ( Autocomplete and also pylint. ) However, these guys could be identified and parsed normally in Spyder. 

For instances,  

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('Cc1ccccc1C')
print mol.GetNumAtoms()
```

> [pylint] E1101:Module 'rdkit.Chem' has no 'MolFromSmiles' member

The above function `MolFromSmiles` is in the `Chem/rdmolfiles.pyd` file.  The function `MolFromInchi` in the `Chem/inchi.py` can be parsed and autocomplete normally. 

## Expected  behavior

Correct Autocomplete and Lint

## Steps to reproduce:  
-  In conda, install rdkit: `conda install -c rdkit rdkit`
-  Editing a file containing above codes.

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment] 2017-10-26 15:12
Please could you try looking the above file using outline from the command line? Let me know if that works?

What is the path to the python environment that contains the above module?

**Comment by platinhom** [comment] 2017-10-27 01:46
@DonJayamanne Do you mean the output of pylint for above codes? 

The pythonPath is set to `C:\\Users\\Hom\\Anaconda2\\python.exe` in  vscode.
And the file is `/c/Users/Hom/Anaconda2/Lib/site-packages/rdkit/Chem/rdmolfiles.pyd` . Indeed, the file `/c/Users/Hom/Anaconda2/Lib/site-packages/rdkit/Chem/inchi.py` can be parsed normally.

```
************* Module hi
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Invalid constant name "mol" (invalid-name)
E:  4, 6: Module 'rdkit.Chem' has no 'MolFromSmiles' member (no-member)
```

**Comment by DonJayamanne** [comment] 2017-10-27 03:05
>/c/Users/Hom/Anaconda2/Lib/site-packages/rdkit/Chem/inchi.py can be parsed normally.

Do you mean to say linting this using pylint in the command line works as expected?

**Comment by platinhom** [comment] 2017-10-27 04:16
@DonJayamanne Yes. Another module works as expected, except the module compiled in pyd file format.    

I have solved this problem.  When I add  `C:\Users\Hom\Anaconda2` into Window system environment `$PATH`, it works for all modules in VS Code. If I unset this path in Window $PATH and only set it in vscode `python.pythonPath`, it failed to work for the module in pyd format wrapped by Boost.Python.

Strangely, even the Anaconda path is in $PATH, the pylint in command line still can't recognize `MolFromSmiles` in rdmolfiles.pyd and gave the same results as above.

**Comment by DonJayamanne** [comment] 2017-10-27 04:24
>the pylint in command line still can't recognize MolFromSmiles in rdmolfiles.pyd and gave the same results as above.

Great, makes sense.
I believe the problem is pylint isn't installed in the above conda environment. You might want to check this. Closing as this isn't an issue with the extension and you have also managed to get it working.

**Closed by DonJayamanne** 2017-10-27 04:24 UTC

**Comment by riccardosabatini** [comment] 2018-09-04 16:14
Same problem here - and I can confirm pylint is installed in the conda environment used
