### ISSUE TITLE
looking for a definition of a function decorated with @ lru_cache.lru_cache

### ISSUE THREAD

**Issue by chanchancl** [DonJayamanne/pythonVSCode#820] opened 2017-03-14 09:11 UTC
OS:Win10
VS Code:1.10.2
Python : 3.5.2
Python extension : 0.6.0

In Django
When I look for a definition of a function decorated with @ lru_cache.lru_cache, it is navigated to a wrong place (_lru_cache_wrapper.wrapper in functools.py) and is not the definition of the function I am looking for.

lru_cache in django.utils
the function I am looking for is django.urls.resolvers.get_resolver

PS:
- View the definition (Alt + F12), sometimes you can find the correct definition, but sometimes it can not.
- Go to definition (F12) and does not work properly.
- I move django source code to other place.

![qq 20170314170526](https://cloud.githubusercontent.com/assets/11457297/23893221/aa940902-08d8-11e7-8f67-8d5d43bda41c.png)

![image](https://cloud.githubusercontent.com/assets/11457297/23893172/78ebd3ee-08d8-11e7-9aa5-fed4bd711971.png)

**Comment by zackkitzmiller** [comment] 2017-03-15 18:24
I believe this is a dupe of https://github.com/DonJayamanne/pythonVSCode/issues/742

**Comment by DonJayamanne** [comment] 2017-04-06 12:43
Duplicate of https://github.com/DonJayamanne/pythonVSCode/issues/742

Thanks @zackkitzmiller

**Closed by DonJayamanne** 2017-04-06 12:43 UTC
